Repository lilacai/lilac, pull requests merged in 2023-09, with the labels that each got.

#636 Fix the async bug when starting the server
  lilac/server.py
Labels: backend

#632 Fix bug with non-serializable schema in the concept labeler.
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend

#631 Update the global project config during changes.
  lilac/config.py
  lilac/data/dataset.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_config_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_project_test.py
  lilac/data/dataset_test.py
  lilac/data/dataset_test_utils.py
  lilac/data_loader.py
  lilac/data_loader_test.py
  lilac/project.py
  lilac/schema.py
  lilac/server_dataset_test.py
  lilac/source.py
  lilac/sources/csv_source.py
  lilac/sources/csv_source_test.py
  lilac/sources/gmail_source.py
  lilac/sources/huggingface_source.py
  lilac/sources/huggingface_source_test.py
  lilac/sources/json_source.py
  lilac/sources/json_source_test.py
  lilac/sources/langsmith.py
  lilac/sources/pandas_source.py
  lilac/sources/pandas_source_test.py
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
  lilac/sources/reddit_hf_source.py
  lilac/sources/source_registry.py
  lilac/sources/source_registry_test.py
  lilac/utils.py
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/DatasetManifest.ts
  web/lib/fastapi_client/models/Source.ts
Labels: backend, client lib

#637 Remove the explicit cache directory for sentence transformers.
  lilac/embeddings/transformer_utils.py
Labels: backend

#639 Fix bug with concept labeler not returning refreshed results.
  web/blueprint/src/lib/components/concepts/labeler/ConceptLabeler.svelte
Labels: frontend

#644 Add expandable metadata
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/ItemMetadataField.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/components/signals/SignalView.svelte
  web/blueprint/src/lib/stores/datasetStore.ts
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/datasets/+page.svelte
Labels: frontend

#655 When merging floats, check for closeness to avoid precision issues. Pin pandas version.
  lilac/data/dataset_duckdb.py
  lilac/embeddings/transformer_utils.py
  poetry.lock
  pyproject.toml
Labels: backend

#656 Fix `RuntimeError` in HNSW index
  lilac/embeddings/vector_store_hnsw.py
Labels: backend

#658 Fix negative-sentiment and legal-terminal concepts due to missing top-level `version` field
  lilac/concepts/legal-termination/concept.json
  lilac/concepts/negative-sentiment/concept.json
Labels: backend

#659 Expand parts of metadata according to the search context
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/ItemMetadataField.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/components/signals/SignalView.svelte
  web/blueprint/src/lib/view_utils.ts
  web/lib/src/schema.ts
Labels: frontend, client lib

#662 Fix italics for N/A
  web/blueprint/src/lib/components/datasetView/ItemMetadataField.svelte
Labels: frontend

#663 Update homepage with short 10sec videos
  docs/.firebaserc
  docs/_static/lilac-welcome.mp4
  docs/_static/welcome/concepts.mp4
  docs/_static/welcome/download.mp4
  docs/_static/welcome/insights.mp4
  docs/_static/welcome/semantic-search.mp4
  docs/_static/welcome/signals.mp4
  docs/getting_started/installation.md
  docs/getting_started/quickstart.md
  docs/welcome.md
  lilac/cli.py
  notebooks/API.ipynb
  scripts/deploy_website.sh
  web/blueprint/src/lib/components/TaskStatus.svelte
  web/blueprint/src/lib/components/datasets/huggingface/ConfigInput.svelte
  web/blueprint/src/lib/components/datasets/huggingface/SplitsInput.svelte
Labels: frontend, backend

#666 Optional Outputs
  lilac/sources/langsmith.py
Labels: backend

#667 Add the python API for adding labels.
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
  lilac/db_manager.py
  poetry.lock
  pyproject.toml
Labels: backend

#671 Fix bug with the selectRows cache not being cleared when labeling concepts in HF.
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend

#668 Improve the project API and documentation.
  .env
  README.md
  development.md
  docs/datasets/dataset_load.md
  docs/getting_started/quickstart_python.md
  docs/huggingface/huggingface_spaces.md
  docs/index.rst
  docs/projects/projects.md
  docs/signals/signals_create.md
  docs/welcome.md
  lilac/__init__.py
  lilac/cli.py
  lilac/concepts/db_concept.py
  lilac/concepts/db_concept_test.py
  lilac/config.py
  lilac/conftest.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_project_test.py
  lilac/data_loader.py
  lilac/db_manager.py
  lilac/env.py
  lilac/load.py
  lilac/load_test.py
  lilac/project.py
  lilac/project_test.py
  lilac/router_data_loader.py
  lilac/router_dataset.py
  lilac/server.py
  lilac/server_concept_test.py
  lilac/server_dataset_test.py
  lilac/server_signal_test.py
  lilac/signals/concept_labels_test.py
  lilac/signals/concept_scorer_test.py
  lilac/sources/duckdb_utils.py
  lilac/sources/gmail_source.py
  lilac/utils.py
  run_server_dev.sh
  scripts/deploy_hf.py
Labels: enhancement, backend

#673 Remove the extra query the entire dataset query.
  lilac/data/dataset_duckdb.py
Labels: backend

#669 Add a large guide for querying datasets.
  docs/datasets/dataset_explore.md
  docs/datasets/dataset_query.md
  docs/index.rst
  lilac/__init__.py
  lilac/data/__init__.py
Labels: backend

#670 Add UI for viewing labels.
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
  lilac/schema.py
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/ItemMetadataField.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/lib/fastapi_client/models/Field.ts
  web/lib/src/lilac.ts
Labels: frontend, backend, client lib

#674 Re-design the items
  docker_start.py
  docs/concepts/concept_technical.md
  lilac/data_loader_test.py
  scripts/deploy_demo.py
  scripts/deploy_hf.py
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
Labels: frontend, backend

#675 Add line height to the media header.
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
Labels: frontend

#676 Add "More like this" button in the item viewer
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
Labels: frontend

#677 Tiny CSS fixes to make mobile not terrible
  scripts/deploy_website.py
  web/blueprint/src/lib/components/HuggingFaceSpaceWelcome.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/stores/navigationStore.ts
  web/lib/src/utils.ts
Labels: frontend, client lib

#678 Use sqlite instead of jsonl for labels.
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
  pytest.ini
Labels: backend

#679 Add simple labeling functionality in the item viewer
  lilac/auth.py
  lilac/router_dataset.py
  lilac/schema.py
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/AddLabelsOptions.ts
  web/lib/fastapi_client/models/DatasetUserAccess.ts
  web/lib/fastapi_client/services/DatasetsService.ts
  web/lib/src/lilac.ts
Labels: frontend, backend, client lib

#680 Add removing labels, and add row_ids to add labels.
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
Labels: backend

#681 Fix REST API with new labels API.
  lilac/router_dataset.py
Labels: backend

#682 Improving the label download
  lilac/router_dataset.py
  poetry.lock
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/datasetView/DownloadFieldList.svelte
  web/blueprint/src/lib/components/datasetView/DownloadModal.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/ItemMetadataField.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/lib/fastapi_client/services/DatasetsService.ts
Labels: frontend, backend, client lib

#684 Expose `LangSmithSource` to the public API and docs
  lilac/sources/__init__.py
Labels: backend

#683 Fix issue with overflow on text
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
Labels: frontend

#687 Add a 'label all' button to label all results in view
  web/blueprint/src/lib/components/datasetView/AddLabel.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
Labels: frontend

#688 Separate metadata requests into a single request for row_ids, and multiple for metadata.
  web/blueprint/src/lib/components/datasetView/AddLabel.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend

#691 Add better error messaging when inferring schema
  lilac/config.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_groups_test.py
  lilac/data/dataset_utils.py
  lilac/data_loader.py
  lilac/schema.py
  lilac/utils.py
Labels: backend

#692 Add docs for labeling. Fix some labeling issues.
  docs/_static/dataset/dataset_add_label_all_button.png
  docs/_static/dataset/dataset_add_label_all_short.png
  docs/_static/dataset/dataset_add_label_download.png
  docs/_static/dataset/dataset_add_label_filter.png
  docs/_static/dataset/dataset_add_label_filter_characters.png
  docs/_static/dataset/dataset_add_label_filter_readability.png
  docs/_static/dataset/dataset_add_label_label_all_button.png
  docs/_static/dataset/dataset_add_label_row.png
  docs/_static/dataset/dataset_add_label_row_tagged.png
  docs/_static/dataset/dataset_add_label_searchbox.png
  docs/_static/dataset/dataset_add_label_short_labels.png
  docs/_static/dataset/dataset_add_label_tag.png
  docs/datasets/dataset_labels.md
  docs/index.rst
  docs/poetry.lock
  docs/pyproject.toml
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_test.py
  web/blueprint/src/lib/components/datasetView/AddLabel.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend, backend

#696 Fix bug with UDFs after metadata separation
  lilac/data/dataset_duckdb.py
  lilac/embeddings/transformer_utils.py
  lilac/schema.py
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend, backend

#698 Allow `add_labels` and `remove_labels` without selection
  docker_start.py
  lilac/concepts/concept_test.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
Labels: backend

#700 Fix UI regression and empty `lilac.yml` (no datasets)
  .env
  lilac/config.py
  lilac/project.py
  web/blueprint/src/lib/components/JSONSchema/JSONSchemaInput.svelte
Labels: frontend, backend

#701 Make '.' the default project.
  .env
  lilac/env.py
  lilac/sources/langsmith.py
Labels: backend

#704 Fix semantic search on repeated
  lilac/router_dataset.py
  lilac/schema.py
  lilac/schema_test.py
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/SearchPill.svelte
  web/blueprint/src/lib/components/datasetView/SearchPillHoverBody.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/view_utils.ts
Labels: frontend, backend

#705 Fix syntax error with keyword search
  lilac/signals/substring_search.py
  lilac/signals/substring_search_test.py
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend, backend

#706 Use iterables for compute_signal and compute_embedding.
  lilac.yml
  lilac/batch_utils.py
  lilac/batch_utils_test.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_utils.py
  lilac/data/dataset_utils_test.py
  scripts/test_py.sh
Labels: backend

#709 Write embeddings to the vector store iteratively
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_utils.py
  lilac/embeddings/vector_store.py
  lilac/embeddings/vector_store_hnsw.py
  lilac/embeddings/vector_store_numpy.py
  lilac/embeddings/vector_store_test.py
Labels: backend

#713 Fix bug with span highlighting a repeated field
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#711 Add clustering signal
  lilac/data/dataset_utils.py
  lilac/embeddings/embedding.py
  lilac/embeddings/vector_store.py
  lilac/project.py
  lilac/signal.py
  lilac/signals/cluster_dbscan.py
  lilac/signals/cluster_dbscan_test.py
  lilac/signals/default_signals.py
  lilac/signals/semantic_similarity.py
  web/blueprint/src/lib/components/JSONSchema/JSONSchemaInput.svelte
  web/blueprint/src/lib/stores/urlHashStore.ts
Labels: frontend, backend

#715 Improve perf of server by removing UUID sort
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
  lilac/router_dataset.py
  web/blueprint/src/lib/components/datasetView/AddLabel.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/lib/fastapi_client/services/DatasetsService.ts
Labels: frontend, backend, client lib

#717 Change the bootup load to be during the new FastAPI lifecycle API.
  lilac/cli.py
  lilac/env.py
  lilac/load.py
  lilac/server.py
  lilac/tasks.py
  scripts/deploy_hf.py
Labels: backend

#718 Migrate the span values to use `__span__` and make the code back-compat
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_utils.py
  lilac/embeddings/embedding.py
  lilac/schema.py
  lilac/schema_test.py
  lilac/splitters/text_splitter_test_utils.py
  web/blueprint/src/lib/components/concepts/labeler_utils.ts
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
  web/blueprint/src/lib/view_utils.spec.ts
  web/blueprint/src/lib/view_utils.ts
  web/lib/src/lilac.ts
  web/lib/src/schema.ts
Labels: frontend, backend, client lib

#720 Rework the huggingface deploy script: part 1
  .gitignore
  lilac/cli.py
  lilac/data/dataset.py
  lilac/env.py
  lilac/hf_docker/.dockerignore
  lilac/hf_docker/.gitignore
  lilac/hf_docker/Dockerfile
  lilac/hf_docker/LICENSE
  lilac/hf_docker/docker_start.sh
  lilac/hf_docker_start.py
  lilac/project.py
  scripts/deploy_hf.py
Labels: backend

#725 Completely overhaul the deploy scripts.
  development.md
  docs/huggingface/huggingface_spaces.md
  lilac.yml
  lilac/__init__.py
  lilac/cli.py
  lilac/deploy.py
  lilac/hf_docker_start.py
  lilac/project.py
  notebooks/API.ipynb
  notebooks/DeployToHuggingFace.ipynb
  poetry.lock
  pyproject.toml
  scripts/deploy_demo.py
  scripts/deploy_hf.py
  scripts/deploy_staging.py
Labels: backend

#726 Improve the schema view to be less overwhelming.
  docs/concepts/concept_metrics.md
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/signals/concept_labels.py
  lilac/signals/concept_labels_test.py
  lilac/signals/concept_scorer.py
  lilac/signals/concept_scorer_test.py
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/lib/fastapi_client/models/ConceptSignal.ts
Labels: frontend, backend, client lib

#727 Add --hf_token and dont require it when we have public datasets, or we set load on start server.
  lilac/cli.py
  lilac/deploy.py
  notebooks/DeployToHuggingFace.ipynb
  scripts/deploy_staging.py
Labels: backend

#729 Fix bug with dataset config on upload.
  lilac/deploy.py
Labels: backend

#728 Improve markdown rendering
  lilac/config.py
  lilac/data/dataset_duckdb.py
  lilac/deploy.py
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/src/lib/view_utils.ts
Labels: frontend, backend
