Repository lilacai/lilac, pull requests merged in 2023-11, with the labels that each got.

#809 Add "not exist" filter when somebody clicks on "N/A" in the histogram
  web/blueprint/src/lib/components/datasetView/FilterPill.svelte
  web/blueprint/src/lib/components/schemaView/FieldDetails.svelte
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#816 Pass token to deploy_project_operations.
  lilac/deploy.py
Labels: backend

#824 Add UI for dataset settings to edit tags of a dataset.
  lilac/config.py
  lilac/db_manager.py
  lilac_hf_space.yml
  scripts/deploy_staging.py
  web/blueprint/src/lib/components/NavigationGroup.svelte
  web/blueprint/src/lib/components/commands/selectors/CommandSelectList.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/lib/view_utils.ts
  web/lib/fastapi_client/models/DatasetSettings.ts
Labels: frontend, backend, client lib

#827 Parquet source: When `pseudo_shuffle=True`, limit the number of shards we read from
  .vscode/extensions.json
  .vscode/settings.json
  docs/datasets/dataset_load.md
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
  poetry.lock
Labels: backend

#826 Add backend support for sampling jsonl files
  lilac/data/dataset_duckdb.py
  lilac/sources/json_source.py
  lilac/sources/json_source_test.py
Labels: backend

#831 Fix the HF deploy script for windows.
  lilac/deploy.py
  lilac/signals/__init__.py
  notebooks/DeployToHuggingFace.ipynb
Labels: backend

#835 Remove redundant dataset_cache call
  lilac/router_dataset.py
Labels: backend

#833 Upgrade Cohere embeddings to v3-light
  lilac/embeddings/cohere.py
  poetry.lock
  pyproject.toml
Labels: backend

#836 Invalidate the query after the redirect to avoid 500 errors from deleted dataset.
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend

#837 Fix dataset uploading on windows.
  lilac/deploy.py
Labels: backend

#838 OpenAI Azure connector
  lilac/embeddings/openai.py
  lilac/router_concept.py
Labels: backend

#840 Expose hbdscan in the docs
  lilac/signals/__init__.py
Labels: backend

#841 Add a query type to SemanticSimilaritySignal and SemanticSearch: 'question' | 'document'
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/embeddings/cohere.py
  lilac/embeddings/embedding.py
  lilac/schema.py
  lilac/signal.py
  lilac/signals/semantic_similarity.py
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/rag/RagRetrieval.svelte
  web/lib/fastapi_client/models/SemanticSearch.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
  web/lib/fastapi_client/models/TextEmbeddingSignal.ts
Labels: frontend, backend, client lib

#842 Fix missing token in hf upload
  lilac/cli.py
  lilac/deploy.py
  scripts/deploy_staging.py
Labels: backend

#843 Add debouncing to file watcher recompilation
  lilac/sources/langsmith.py
  run_server_dev.sh
  web/blueprint/src/lib/queries/langsmithQueries.ts
  web/lib/fastapi_client/services/LangsmithService.ts
Labels: frontend, backend, client lib

#839 Integrate Presidio into PII detection
  lilac/signals/pii.py
  lilac/signals/pii_ip_address.py
  lilac/signals/pii_presidio.py
  lilac/signals/pii_test.py
  mypy.ini
  poetry.lock
  pyproject.toml
Labels: backend

#844 Simplify the UI for choosing media fields
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
Labels: frontend

#845 Add monaco and enable column-level diffing.
  package-lock.json
  web/blueprint/package.json
  web/blueprint/src/lib/components/ButtonDropdown.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/EditLabel.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaDiff.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/monaco.ts
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/+layout.svelte
Labels: frontend

#847 Add parallelism to dataset.map with dask.
  docs/conf.py
  lilac/conftest.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_test_utils.py
  lilac/signals/pii_presidio.py
  lilac/signals/pii_test.py
  lilac/tasks.py
  lilac/test_utils.py
  mypy.ini
  notebooks/DatasetMap.ipynb
  poetry.lock
  pyproject.toml
  scripts/deploy_demo.py
  scripts/fix_py.sh
  scripts/lint_py.sh
  scripts/make_fastapi_client.py
Labels: backend

#849 Fix bug where missing keys in the filter constraint would raise KeyError
  lilac/embeddings/vector_store.py
  lilac/embeddings/vector_store_test.py
Labels: backend

#848 Pass the job_id to the dataset.map map_fn.
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/schema.py
Labels: backend

#846 Add Single Item as a view type with pagination
  docs/poetry.lock
  lilac/config.py
  lilac/embeddings/openai.py
  lilac/schema.py
  lilac/signal.py
  lilac/source.py
  package-lock.json
  pyproject.toml
  web/blueprint/package.json
  web/blueprint/src/lib/components/datasetView/Chip.svelte
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/PrefetchRowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/ScrollView.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemSelectRows.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/svelte.config.js
  web/lib/fastapi_client/models/DatasetUISettings.ts
Labels: frontend, backend, client lib

#850 Add unit tests for num_jobs=-1
  lilac/data/dataset_map_test.py
  lilac/tasks.py
  notebooks/DatasetMap.ipynb
Labels: backend

#852 Fix thread bug in hnswlib, which should fix CI python tests
  lilac/embeddings/vector_store_hnsw.py
Labels: backend

#853 Fix bugs with the media fields selector where no fields showed up.
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
Labels: frontend

#855 Small fix with rendering `MetadataSearch` in the schema view
  web/blueprint/src/lib/components/datasetView/SearchPill.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
Labels: frontend

#854 Fast dataset load
  lilac/__init__.py
  lilac/config.py
  lilac/data/dataset.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_config_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_project_test.py
  lilac/data/dataset_test.py
  lilac/data/dataset_test_utils.py
  lilac/data/dataset_utils.py
  lilac/load_dataset.py
  lilac/load_dataset_test.py
  lilac/load_test.py
  lilac/router_data_loader.py
  lilac/server.py
  lilac/server_dataset_test.py
  lilac/source.py
  lilac/source_test.py
  lilac/sources/csv_source.py
  lilac/sources/csv_source_test.py
  lilac/sources/default_sources.py
  lilac/sources/dict_source.py
  lilac/sources/dict_source_test.py
  lilac/sources/github_source.py
  lilac/sources/gmail_source.py
  lilac/sources/huggingface_source.py
  lilac/sources/huggingface_source_test.py
  lilac/sources/json_source.py
  lilac/sources/json_source_test.py
  lilac/sources/langsmith.py
  lilac/sources/llama_index_docs_source.py
  lilac/sources/llama_index_docs_source_test.py
  lilac/sources/pandas_source.py
  lilac/sources/pandas_source_test.py
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
  lilac/sources/reddit_hf_source.py
  lilac/sources/source_registry.py
  lilac/sources/sqlite_source.py
  lilac/sources/sqlite_source_test.py
Labels: backend

#856 Fix a bug with single item mode and monaco diff not updating
  lilac/__init__.py
  lilac/embeddings/__init__.py
  lilac/signals/__init__.py
  lilac/sources/__init__.py
  web/blueprint/src/lib/components/datasetView/ItemMediaDiff.svelte
Labels: frontend, backend

#858 Add jsonl intermediate caching to signals. Introduce a central spot for this cache abstraction.
  lilac/data/dataset.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_config_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_map_test.py
  lilac/load.py
  lilac/router_dataset.py
  lilac/schema.py
  lilac/schema_test.py
  lilac/tasks.py
  lilac/test_utils.py
Labels: backend

#860 Implement fast_process for parquet sources
  lilac/load_dataset_test.py
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
Labels: backend

#862 Rename fast_process to load_to_parquet
  development.md
  lilac/load_dataset.py
  lilac/load_dataset_test.py
  lilac/source.py
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
Labels: backend

#863 Implement CSV direct to parquet
  lilac/load_dataset_test.py
  lilac/sources/csv_source.py
  lilac/sources/csv_source_test.py
  lilac/sources/parquet_source_test.py
  lilac/test_utils.py
Labels: backend

#865 Implement fast json source
  lilac/sources/json_source.py
  lilac/sources/json_source_test.py
Labels: backend

#866 Add a nest_under field to dataset.map().
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_labels_test.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_test.py
  lilac/schema.py
  lilac/schema_test.py
  lilac/server_dataset_test.py
  lilac/tasks.py
  notebooks/DatasetMap.ipynb
Labels: backend

#870 Add `map<key, value>` dtype. No support in the UI yet.
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_utils.py
  lilac/load_dataset_test.py
  lilac/schema.py
  lilac/schema_test.py
  lilac/signals/text_statistics_test.py
  lilac/source.py
  lilac/sources/huggingface_source.py
  lilac/sources/parquet_source_test.py
  notebooks/API.ipynb
  web/blueprint/src/lib/components/commands/CommandCreateConcept.svelte
  web/blueprint/src/lib/components/concepts/DatasetFieldEmbeddingSelector.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/ExportModal.svelte
  web/blueprint/src/lib/components/datasetView/FieldList.svelte
  web/blueprint/src/lib/components/datasetView/GroupByPill.svelte
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasetView/SortPill.svelte
  web/blueprint/src/lib/components/datasetView/SpanHoverTooltip.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/lib/view_utils.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ConceptSearch.ts
  web/lib/fastapi_client/models/DataType.ts
  web/lib/fastapi_client/models/Field.ts
  web/lib/fastapi_client/models/KeywordSearch.ts
  web/lib/fastapi_client/models/MapType.ts
  web/lib/fastapi_client/models/MetadataSearch.ts
  web/lib/fastapi_client/models/SemanticSearch.ts
  web/lib/src/lilac.spec.ts
  web/lib/src/lilac.ts
  web/lib/src/schema.ts
Labels: frontend, backend, client lib

#869 Implement fast processing for huggingface datasets
  lilac/sources/huggingface_source.py
  lilac/sources/huggingface_source_test.py
Labels: backend

#873 Avoid computing stats for every single field on page load
  web/blueprint/src/lib/components/datasetView/GroupByPill.svelte
  web/lib/fastapi_client/models/MapType.ts
Labels: frontend, client lib

#874 Fix a sample_size yaml bug
  lilac/deploy.py
  lilac/sources/parquet_source.py
Labels: backend

#875 UI fixes for expanding long rows.
  web/blueprint/src/lib/components/ButtonDropdown.svelte
  web/blueprint/src/lib/components/common/Hoist.ts
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaDiff.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
Labels: frontend

#877 Fix small bug with compute signal / concepts and filtering by valid dtypes.
  web/blueprint/src/lib/components/commands/CommandConcepts.svelte
  web/blueprint/src/lib/components/commands/CommandSignals.svelte
  web/blueprint/src/lib/components/commands/selectors/FieldSelect.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
Labels: frontend

#879 Fix a bug with previewing and comparing on repeated values.
  web/blueprint/src/lib/components/ButtonDropdown.svelte
  web/blueprint/src/lib/components/common/Hoist.ts
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/EditLabel.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
Labels: frontend

#880 Allow custom signals to work with dask processes.
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/router_dataset.py
  lilac/tasks.py
  poetry.lock
  pyproject.toml
Labels: backend

#882 Add support for input paths to dataset.map.
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/schema.py
  web/lib/fastapi_client/models/MapInfo.ts
Labels: backend, client lib

#883 Improve ergonomics of map, relaxing the exact requirement of kwargs={row, job_id}
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/schema.py
  notebooks/DatasetMap.ipynb
Labels: backend

#884 Upgrade duckdb to 0.9.2, fixing a crash in a dask process with fetch_df_chunk.
  lilac/data/dataset_duckdb.py
  poetry.lock
  pyproject.toml
Labels: backend

#885 Pass explicit schema during jsonl -> parquet conversion
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/schema_duckdb.py
  web/blueprint/src/lib/components/datasetView/GroupByPanel.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/schemaView/FieldDetails.svelte
  web/lib/src/schema.ts
Labels: frontend, backend, client lib

#886 Fix span resolving for map outputs
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
Labels: backend

#887 Rename `lilac.lilac_span` to `lilac.span`
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_utils.py
  lilac/schema.py
  lilac/server_concept_test.py
  lilac/signals/cluster_dbscan.py
  lilac/signals/cluster_dbscan_test.py
  lilac/signals/cluster_hdbscan.py
  lilac/signals/cluster_hdbscan_test.py
  lilac/signals/concept_labels.py
  lilac/signals/concept_labels_test.py
  lilac/signals/concept_scorer.py
  lilac/signals/lang_detection.py
  lilac/signals/lang_detection_test.py
  lilac/signals/ner.py
  lilac/signals/pii_presidio.py
  lilac/signals/pii_secrets.py
  lilac/signals/semantic_similarity.py
  lilac/signals/semantic_similarity_test.py
  lilac/signals/substring_search.py
  lilac/splitters/text_splitter_test_utils.py
  lilac/splitters/text_splitter_test_utils_test.py
  notebooks/DatasetMap.ipynb
Labels: backend

#890 Prefer existing embedding in embedding retrieval function
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#888 Add rendering of string spans that were derived from a map with input path
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/view_utils.ts
  web/lib/src/schema.ts
Labels: frontend, client lib

#892 Add string filters
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_filter_test.py
  lilac/router_dataset.py
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/datasetView/FilterPill.svelte
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/AddLabelsOptions.ts
  web/lib/fastapi_client/models/MetadataSearch.ts
  web/lib/fastapi_client/models/RemoveLabelsOptions.ts
  web/lib/fastapi_client/models/SelectGroupsOptions.ts
  web/lib/fastapi_client/models/SelectRowsOptions.ts
  web/lib/fastapi_client/models/StringFilter.ts
  web/lib/src/lilac.ts
Labels: frontend, backend, client lib

#893 Make the tags & namespaces in the dataset panel expandable.
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/NavigationCategory.svelte
  web/blueprint/src/lib/components/NavigationExpandable.svelte
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#894 Fix UI bugs with span rendering of maps.
  lilac/data/dataset_duckdb.py
  web/blueprint/src/lib/components/ButtonDropdown.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
Labels: frontend, backend

#895 Make schema in signals optional
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_utils.py
  lilac/signal.py
Labels: backend

#896 Add the navigation store to the URL hash.
  web/blueprint/src/lib/stores/navigationStore.ts
  web/blueprint/src/lib/stores/urlHashStore.ts
  web/blueprint/src/routes/+layout.svelte
Labels: frontend

#898 Make the tag expandables serializable in the URL for sharing.
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/NavigationCategory.svelte
  web/blueprint/src/lib/components/NavigationExpandable.svelte
  web/blueprint/src/lib/stores/navigationStore.ts
  web/blueprint/src/lib/stores/urlHashStore.ts
Labels: frontend

#899 Allow lilac to run tasks outside a running event loop.
  lilac/tasks.py
  lilac/tasks_test.py
Labels: backend

#901 Fix trailing error with tests.
  lilac/tasks_test.py
Labels: backend

#900 Refactor dataset/signal endpoints into separate module
  lilac/router_dataset.py
  lilac/router_dataset_signals.py
  lilac/server.py
  lilac/server_dataset_signals_test.py
  lilac/server_dataset_test.py
  web/lib/fastapi_client/services/DatasetsService.ts
Labels: backend, client lib

#904 Improve the UI for repeated values.
  web/blueprint/src/lib/components/ButtonDropdown.svelte
  web/blueprint/src/lib/components/common/Hoist.ts
  web/blueprint/src/lib/components/datasetView/ExportModal.svelte
  web/blueprint/src/lib/components/datasetView/FilterPill.svelte
  web/blueprint/src/lib/components/datasetView/GroupByPill.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaDiff.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasetView/SearchPill.svelte
  web/blueprint/src/lib/components/datasetView/SearchPillHoverBody.svelte
  web/blueprint/src/lib/components/datasetView/SortPill.svelte
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#907 Fix keyword search to work with apostrophe `'`
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_search_test.py
Labels: backend
