Repository lilacai/lilac, pull requests merged in 2023-12, with the labels that each got.

#909 Small ergonomic fixes while writing the "code formatting" blog post
  lilac/config.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  web/blueprint/src/lib/components/GettingStarted.svelte
  web/lib/fastapi_client/models/DatasetSettings.ts
Labels: frontend, backend, client lib

#910 Merge multiple shards of the same task into the same progress bar.
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_utils.py
  lilac/tasks.py
  web/blueprint/src/lib/stores/taskMonitoringStore.ts
  web/lib/fastapi_client/models/TaskStepInfo.ts
  web/lib/fastapi_client/models/TaskType.ts
Labels: frontend, backend, client lib

#911 Add server-side RAG python code.
  lilac/__init__.py
  lilac/embeddings/openai.py
  lilac/gen/__init__.py
  lilac/gen/generator_openai.py
  lilac/load_dataset.py
  lilac/rag/__init__.py
  lilac/rag/rag.py
  lilac/router_concept.py
  lilac/router_rag.py
  lilac/signals/default_signals.py
  lilac/sources/github_source.py
  lilac/text_gen.py
  mypy.ini
  notebooks/Rag.ipynb
  poetry.lock
  pyproject.toml
  web/blueprint/src/routes/rag/+page.svelte
Labels: frontend, backend

#912 Add blog post for diffing and `dataset.map`
  Dockerfile
  docs/_static/better_curate_blog/compare.mp4
  docs/_static/better_curate_blog/filter_items.mp4
  docs/_static/better_curate_blog/open-dataset.png
  docs/blog/better-curate.md
  docs/poetry.lock
  lilac/data/dataset.py
  lilac/env.py
  notebooks/BetterWayToCurate.ipynb
  package-lock.json
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetLoadingPage.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/components/datasetView/SortPill.svelte
  web/blueprint/src/lib/view_utils.ts
  web/lib/fastapi_client/models/BinaryFilter.ts
  web/lib/fastapi_client/models/MetadataSearch.ts
Labels: frontend, backend, client lib

#918 Add spec for select options
  lilac/data/dataset_duckdb.py
Labels: backend

#916 Improve the RAG UI
  lilac/gen/generator_openai.py
  lilac/rag/rag.py
  lilac/router_rag.py
  lilac/text_gen.py
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/Expandable.svelte
  web/blueprint/src/lib/components/rag/RagPrompt.svelte
  web/blueprint/src/lib/components/rag/RagRetrieval.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/routes/rag/+page.svelte
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/RagGenerationResult.ts
  web/lib/fastapi_client/services/RagService.ts
Labels: frontend, backend, client lib

#919 Simplify helper methods to closer align to API for select options
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  scripts/deploy_website.py
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/datasetView/FilterPill.svelte
  web/lib/fastapi_client/models/MetadataSearch.ts
  web/lib/fastapi_client/models/StringFilter.ts
Labels: frontend, backend, client lib

#920 Add threaded task execution.
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/load.py
  lilac/router_data_loader.py
  lilac/router_dataset_signals.py
  lilac/server.py
  lilac/tasks.py
  lilac/tasks_test.py
  poetry.lock
  pyproject.toml
Labels: backend

#924 Start writing the query options compiler
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/gen/generator_openai.py
Labels: backend

#923 Add a guide for iterating on dataset
  docs/_static/better_curate_blog/compare.mp4
  docs/_static/better_curate_blog/filter_items.mp4
  docs/_static/curate_coding_dataset/compare.png
  docs/_static/curate_coding_dataset/filter_metadata.png
  docs/_static/curate_coding_dataset/open-dataset.png
  docs/_static/custom.js
  docs/_static/dataset/company_name_span.mp4
  docs/_static/dataset/filter_metadata.mp4
  docs/_static/dataset/nested_schema.png
  docs/blog/curate-coding-dataset.md
  docs/datasets/dataset_iterate.md
  docs/datasets/dataset_labels.md
  docs/datasets/dataset_query.md
  docs/index.rst
  docs/poetry.lock
  lilac/__init__.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_test.py
  lilac/load_dataset.py
  lilac/sources/__init__.py
  notebooks/CurateCodingDataset.ipynb
  poetry.lock
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
Labels: frontend, backend

#925 Make sure the results of dataset.map() always returns an iterable.
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
Labels: backend

#931 Fix css style for markdown tables
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/JSONSchema/JSONSchemaInput.svelte
  web/blueprint/src/lib/components/commands/CommandConcepts.svelte
  web/blueprint/src/lib/components/commands/CommandSignals.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/signals/SignalView.svelte
  web/blueprint/src/routes/rag/+page.svelte
Labels: frontend

#932 Redo the docs.lilacml.com landing page
  README.md
  docs/_static/curate_coding_dataset/label.png
  docs/blog/curate-coding-dataset.md
  docs/datasets/dataset_edit.md
  docs/index.rst
  docs/welcome.md
  web/blueprint/src/lib/components/HuggingFaceSpaceWelcome.svelte
Labels: frontend

#935 Add support for arbitrary value type `v` in `map<k, v>` in parquet
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_groups_test.py
  lilac/data/dataset_select_rows_filter_test.py
  lilac/data/dataset_stats_test.py
  lilac/data/dataset_test.py
  lilac/schema.py
  lilac/schema_duckdb.py
  lilac/schema_test.py
  lilac/sources/parquet_source_test.py
  web/lib/fastapi_client/models/MapType.ts
Labels: backend, client lib

#929 Fix tqdm progress bars by separating report_progress from show_progress.
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/load_dataset.py
  lilac/tasks.py
  web/lib/fastapi_client/models/TaskStepInfo.ts
Labels: backend, client lib

#933 Add dataset.map support for limit/filter
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_utils.py
  lilac/tasks.py
Labels: backend

#934 Add batch size support and collapse transform impl
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
Labels: backend

#938 Small tweaks to improve the glaive dataset blog post.
  docs/_static/curate_coding_dataset/glaive_preview.png
  docs/blog/curate-coding-dataset.md
  lilac/data/dataset_duckdb.py
  lilac/tasks.py
  lilac_hf_space.yml
  notebooks/CurateCodingDataset.ipynb
Labels: backend

#944 Make the signal "try it" page work for signals w/o schema
  lilac/router_signal.py
  pyproject.toml
  web/blueprint/src/lib/components/signals/SignalView.svelte
  web/lib/fastapi_client/models/SignalSchemaResponse.ts
  web/lib/src/lilac.ts
Labels: frontend, backend, client lib

#946 Fix UI bugs: monaco scroll, hash state forgotten, compare non-media fields
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/NavigationCategory.svelte
  web/blueprint/src/lib/components/NavigationExpandable.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaDiff.svelte
  web/blueprint/src/lib/stores/urlHashStore.ts
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#948 Infer dataset formats. Start with just ShareGPT.
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_format.py
  lilac/data/dataset_format_test.py
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/DatasetFormat.ts
  web/lib/fastapi_client/models/DatasetManifest.ts
Labels: backend, client lib

#950 Add UI for title slots for ShareGPT.
  lilac/data/dataset_format.py
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/lib/fastapi_client/models/DatasetFormat.ts
Labels: frontend, backend, client lib

#952 Switch to monaco for the main viewer.
  package-lock.json
  web/blueprint/package.json
  web/blueprint/src/app.html
  web/blueprint/src/lib/components/concepts/ConceptPreview.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaDiff.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/datasetView/insights/ConceptInsightItems.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
  web/blueprint/src/lib/components/signals/SignalView.svelte
  web/blueprint/src/lib/monaco.ts
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#951 Add special support for a DELETED label
  lilac/data/dataset.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_labels_test.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_select_groups_test.py
  lilac/data/dataset_select_rows_filter_test.py
  lilac/data/dataset_stats_test.py
  lilac/router_dataset.py
Labels: backend

#956 Simplify monaco viewer. Add support for deep linking.
  package-lock.json
  web/blueprint/package.json
  web/blueprint/src/app.html
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
  web/blueprint/src/lib/monaco.ts
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/src/routes/+layout.svelte
Labels: frontend

#957 Fix bug with loading dataset and settings.
  web/blueprint/src/lib/components/datasetView/DatasetLoadingPage.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend

#955 Drive-by cleanup of schema.py code
  lilac/schema.py
Labels: backend

#958 Fix a bug where we highlighted all concept spans regardless of their score.
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
Labels: frontend

#959 Eliminate setup count call from parquet_source.
  lilac/source.py
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
Labels: backend

#947 Using `loky` (thin wrapper around `multiprocessing`) instead of dask
  .env
  .vscode/settings.json
  docs/deployment/huggingface_spaces.md
  lilac/conftest.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_test_utils.py
  lilac/env.py
  lilac/load.py
  lilac/load_dataset.py
  lilac/load_dataset_test.py
  lilac/load_test.py
  lilac/router_dataset_signals.py
  lilac/router_tasks.py
  lilac/server.py
  lilac/source.py
  lilac/sources/csv_source.py
  lilac/sources/csv_source_test.py
  lilac/sources/huggingface_source.py
  lilac/sources/huggingface_source_test.py
  lilac/sources/json_source.py
  lilac/sources/json_source_test.py
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
  lilac/tasks.py
  mypy.ini
  poetry.lock
  pyproject.toml
  pytest.ini
  web/blueprint/src/lib/components/TaskStatus.svelte
  web/blueprint/src/lib/components/datasetView/DatasetLoadingPage.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/TaskInfo.ts
  web/lib/fastapi_client/models/TaskShardInfo.ts
  web/lib/fastapi_client/models/TaskStepInfo.ts
Labels: frontend, backend, client lib

#961 Reduce import times
  development.md
  lilac/concepts/concept.py
  lilac/signals/cluster_hdbscan.py
  lilac/signals/minhash_dup.py
  lilac/signals/semantic_similarity.py
  lilac/splitters/spacy_splitter.py
  lilac/utils.py
  poetry.lock
  pyproject.toml
Labels: backend

#964 Fix broken doc links.
  README.md
  docs/blog/introducing-lilac.md
  docs/index.rst
  docs/projects/projects.md
  lilac/project.py
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/GettingStarted.svelte
  web/blueprint/src/lib/components/HuggingFaceSpaceWelcome.svelte
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/routes/datasets/new/+page.svelte
Labels: frontend, backend

#962 Add sugar for `ll.from_huggingface()`
  lilac/__init__.py
  lilac/load_dataset.py
  lilac/load_dataset_test.py
  lilac/sources/huggingface_source.py
Labels: backend

#966 Add Jina V2 embeddings
  lilac/data/dataset_test_utils.py
  lilac/embeddings/embedding.py
  lilac/embeddings/jina.py
  lilac/project.py
  lilac/schema.py
  lilac/signals/default_signals.py
  lilac/sources/gmail_source.py
  lilac/tasks.py
  mypy.ini
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
Labels: backend, client lib

#968 Add public API `dataset.get_embeddings()`
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_test.py
  lilac/signals/concept_scorer.py
  lilac/sources/csv_source.py
  lilac/sources/huggingface_source.py
  lilac/sources/json_source.py
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
Labels: frontend, backend

#974 Fix memory leak caused by Iterable/Iterator mixups
  lilac/batch_utils.py
  lilac/concepts/db_concept_test.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_config_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_project_test.py
  lilac/data/dataset_select_rows_filter_test.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_test.py
  lilac/data/dataset_utils.py
  lilac/data/dataset_utils_test.py
  lilac/embeddings/cohere.py
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  lilac/embeddings/openai.py
  lilac/embeddings/palm.py
  lilac/embeddings/sbert.py
  lilac/load_test.py
  lilac/server_concept_test.py
  lilac/server_dataset_signals_test.py
  lilac/server_dataset_test.py
  lilac/server_signal_test.py
  lilac/signal.py
  lilac/signal_test.py
  lilac/signals/cluster_dbscan.py
  lilac/signals/cluster_dbscan_test.py
  lilac/signals/cluster_hdbscan.py
  lilac/signals/cluster_hdbscan_test.py
  lilac/signals/concept_labels.py
  lilac/signals/concept_scorer.py
  lilac/signals/concept_scorer_test.py
  lilac/signals/filter_mask.py
  lilac/signals/lang_detection.py
  lilac/signals/near_dup.py
  lilac/signals/ner.py
  lilac/signals/pii.py
  lilac/signals/semantic_similarity.py
  lilac/signals/semantic_similarity_test.py
  lilac/signals/substring_search.py
  lilac/signals/text_statistics.py
  lilac/tasks.py
  lilac/utils.py
Labels: backend

#965 Improve the row header to give us space for deleting.
  web/blueprint/src/lib/components/ButtonDropdown.svelte
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/commands/Commands.svelte
  web/blueprint/src/lib/components/common/DropdownPill.svelte
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/EditLabel.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/GroupByPill.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/LabelPill.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/ScrollView.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/components/datasetView/SortPill.svelte
  web/blueprint/src/routes/+layout.svelte
Labels: frontend

#975 Add color scales for semantic / concept search. Add openchat format.
  lilac/data/dataset_format.py
  lilac/data/dataset_format_test.py
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
Labels: frontend, backend

#980 Remove legal-termination concept.
  docs/blog/introducing-lilac.md
  lilac/concepts/legal-termination/concept.json
  lilac_hf_space.yml
Labels: backend

#977 fix iterable robustness
  lilac/data/dataset_utils.py
  lilac/data/dataset_utils_test.py
Labels: backend

#976 Emit membership prob in HDBScan, and fix "group by" UI bugs
  lilac/signals/cluster_hdbscan.py
  lilac/signals/cluster_hdbscan_test.py
  notebooks/unmaintained/PromptTopics.ipynb
  web/blueprint/src/lib/components/datasetView/GroupByPanel.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
Labels: frontend, backend

#984 Fix `ll.start_server()` and add a test for full end-to-end server startup
  lilac/server.py
  lilac/server_test.py
Labels: backend

#983 Add markdown extractor signal.
  lilac/signals/default_signals.py
  lilac/signals/markdown_code_block.py
  lilac/signals/markdown_code_block_test.py
  notebooks/CurateCodingDataset.ipynb
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
Labels: frontend, backend

#986 Make `ll.start_server()` blocking outside an event loop
  lilac/server.py
Labels: backend

#981 Add `dataset.cluster()`
  lilac/data/dataset.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_test.py
  lilac/data/dataset_utils.py
  lilac/load_test.py
  lilac/project.py
  lilac/router_dataset_signals.py
  lilac/signal.py
  lilac/signal_test.py
  lilac/signals/cluster_dbscan.py
  lilac/signals/cluster_hdbscan.py
  notebooks/unmaintained/PromptTopics.ipynb
  web/blueprint/src/lib/components/contextMenu/SchemaFieldMenu.svelte
  web/blueprint/src/lib/components/datasetView/GroupByPanel.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/lib/fastapi_client/models/ConceptLabelsSignal.ts
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
  web/lib/fastapi_client/models/Signal.ts
  web/lib/fastapi_client/models/SubstringSignal.ts
  web/lib/fastapi_client/models/TextEmbeddingSignal.ts
  web/lib/fastapi_client/models/TextSignal.ts
Labels: frontend, backend, client lib

#991 Use CUDA when available for sentence transformers.
  lilac/embeddings/transformer_utils.py
Labels: backend

#993 Add topic clustering in `dataset.cluster()`
  lilac/batch_utils.py
  lilac/batch_utils_test.py
  lilac/conftest.py
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_utils.py
  lilac/embeddings/jina.py
  lilac/embeddings/openai.py
  lilac/router_signal.py
  lilac/signal.py
  lilac/signals/cluster_hdbscan.py
  lilac/tasks.py
Labels: backend

#995 Use the yaml CLoader loader if it's available.
  lilac/project.py
Labels: backend

#996 Fix jina to also run on CUDA if available
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  lilac/embeddings/sbert.py
  lilac/embeddings/transformer_utils.py
Labels: backend

#997 Use cuml for clustering when possible
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  lilac/embeddings/sbert.py
  lilac/signals/cluster_hdbscan.py
Labels: backend

#998 Allow map to be called for arbitrary depth
  lilac/batch_utils.py
  lilac/batch_utils_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_utils.py
  lilac/data/dataset_utils_test.py
  lilac/server_dataset_signals_test.py
  lilac/sources/parquet_source_test.py
  lilac/splitters/spacy_splitter.py
  poetry.lock
  pyproject.toml
Labels: backend

#999 `dataset.map` can now nest_under any repeated
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_test_utils.py
  lilac/data/dataset_utils.py
Labels: backend

#1000 Make `ds.cluster()` have resumable title generation
  lilac/batch_utils.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
Labels: backend

#1001 Merge `output_column` and `nest_under` --> `dataset.map(output_path=...)`
  docs/blog/curate-coding-dataset.md
  docs/datasets/dataset_edit.md
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_project_test.py
  lilac/signals/pii_test.py
  notebooks/CurateCodingDataset.ipynb
  notebooks/DatasetMap.ipynb
  notebooks/unmaintained/PromptTopics.ipynb
  pyproject.toml
Labels: backend

#994 Fix map
  development.md
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/embeddings/transformer_utils.py
  lilac/load.py
  lilac/load_dataset.py
  lilac/load_dataset_test.py
  lilac/router_data_loader.py
  lilac/router_dataset_signals.py
  lilac/server.py
  lilac/tasks.py
  lilac/tasks_test.py
  poetry.lock
  pyproject.toml
  run_server_dev.sh
  scripts/lint_py.sh
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/TaskInfo.ts
  web/lib/fastapi_client/models/TaskShardInfo.ts
Labels: backend, client lib

#1002 `dataset.cluster()` now uses `transform()` which uses `map()`
  docs/poetry.lock
  lilac/__init__.py
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_utils.py
  lilac/signals/cluster_hdbscan.py
Labels: backend

#1003 Remove TaskShardId
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/load.py
  lilac/router_dataset_signals.py
  lilac/source.py
  lilac/tasks.py
Labels: backend

#1004 Add signal.map customization
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/load_test.py
  lilac/signal.py
  lilac/signal_test.py
Labels: backend

#1005 Make OpenAI calls threaded with exponential backoff
  lilac/data/clustering.py
Labels: backend

#1006 Implement signals on top of the map infrastructure
  lilac/data/dataset_duckdb.py
  lilac/embeddings/__init__.py
  lilac/embeddings/cohere.py
  lilac/embeddings/embedding.py
  lilac/embeddings/embedding_test.py
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  lilac/embeddings/openai.py
  lilac/embeddings/palm.py
  lilac/embeddings/sbert.py
  lilac/signal.py
  lilac/signals/text_statistics.py
Labels: backend

#1007 Allow clustering of a nested path
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset_utils.py
  web/lib/fastapi_client/models/ConceptLabelsSignal.ts
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
  web/lib/fastapi_client/models/Signal.ts
  web/lib/fastapi_client/models/SubstringSignal.ts
  web/lib/fastapi_client/models/TextEmbeddingSignal.ts
  web/lib/fastapi_client/models/TextSignal.ts
Labels: backend, client lib

#1008 remove VectorCompute path in dispatch_workers
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/signal.py
  lilac/signals/cluster_dbscan.py
  lilac/signals/cluster_hdbscan.py
  lilac/signals/concept_scorer.py
  lilac/signals/concept_scorer_test.py
  lilac/signals/semantic_similarity.py
  lilac/signals/semantic_similarity_test.py
  web/lib/fastapi_client/models/ConceptLabelsSignal.ts
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
  web/lib/fastapi_client/models/Signal.ts
  web/lib/fastapi_client/models/SubstringSignal.ts
  web/lib/fastapi_client/models/TextEmbeddingSignal.ts
  web/lib/fastapi_client/models/TextSignal.ts
Labels: backend, client lib
