Repository lilacai/lilac, pull requests merged in 2023-10, with the labels that each got.

#731 Upgrade duckdb to 0.9
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_groups_test.py
  lilac/schema.py
  lilac/splitters/chunk_splitter.py
  poetry.lock
  pyproject.toml
Labels: backend

#732 First prototype of RAG UI.
  lilac/router_rag.py
  lilac/server.py
  lilac/splitters/chunk_splitter.py
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/lib/components/concepts/DatasetFieldEmbeddingSelector.svelte
  web/blueprint/src/lib/components/rag/RagPrompt.svelte
  web/blueprint/src/lib/components/rag/RagRetrieval.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/lib/stores/ragViewStore.ts
  web/blueprint/src/lib/stores/urlHashStore.ts
  web/blueprint/src/routes/+layout.svelte
  web/blueprint/src/routes/rag/+page.svelte
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/services/RagService.ts
Labels: frontend, backend, client lib

#733 Add LILAC_AUTH_ADMIN_EMAILS to set admins.
  lilac/auth.py
  lilac/env.py
  lilac/router_data_loader.py
  lilac/router_dataset.py
  lilac/server.py
  lilac/server_dataset_test.py
  lilac/server_test.py
  lilac/tasks.py
  web/blueprint/src/lib/components/Page.svelte
  web/lib/fastapi_client/models/UserAccess.ts
Labels: frontend, backend, client lib

#734 Add allowing non-admin users to add labels, but not create label types.
  lilac/auth.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
  lilac/env.py
  lilac/router_dataset.py
  lilac/server_dataset_test.py
  lilac/server_test.py
  web/blueprint/src/lib/components/datasetView/AddLabel.svelte
  web/lib/fastapi_client/models/DatasetUserAccess.ts
Labels: frontend, backend, client lib

#735 Add "Group by" mode
  lilac/data/__init__.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/schema.py
  lilac/signals/cluster_dbscan.py
  lilac/signals/cluster_dbscan_test.py
  lilac/signals/filter_mask.py
  lilac/signals/semantic_similarity.py
  web/blueprint/src/lib/components/commands/CommandConcepts.svelte
  web/blueprint/src/lib/components/commands/CommandSignals.svelte
  web/blueprint/src/lib/components/datasetView/AddLabel.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/GroupByDropdown.svelte
  web/blueprint/src/lib/components/datasetView/GroupByPanel.svelte
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasetView/SearchPill.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/src/lib/view_utils.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/AddLabelsOptions.ts
  web/lib/fastapi_client/models/MetadataSearch.ts
  web/lib/fastapi_client/models/RemoveLabelsOptions.ts
  web/lib/fastapi_client/models/SelectRowsOptions.ts
  web/lib/fastapi_client/models/SelectRowsSchemaOptions.ts
  web/lib/fastapi_client/models/SignalInputType.ts
  web/lib/src/lilac.ts
  web/lib/src/schema.ts
Labels: frontend, backend, client lib

#741 Add LILAC_AUTH_USER_DISABLE_LABEL_ALL
  lilac/auth.py
  lilac/env.py
  lilac/router_dataset.py
  lilac/server_test.py
  web/blueprint/src/lib/components/datasetView/AddLabel.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/lib/fastapi_client/models/DatasetUserAccess.ts
Labels: frontend, backend, client lib

#740 Add a github source and a LlamaIndexDocsSource source.
  lilac/__init__.py
  lilac/data/dataset_project_test.py
  lilac/load.py
  lilac/load_dataset.py
  lilac/load_dataset_test.py
  lilac/project.py
  lilac/router_data_loader.py
  lilac/router_rag.py
  lilac/sources/__init__.py
  lilac/sources/default_sources.py
  lilac/sources/github_source.py
  lilac/sources/llama_index_docs_source.py
  lilac/sources/llama_index_docs_source_test.py
  notebooks/LlamaIndexLoader.ipynb
  poetry.lock
  pyproject.toml
  web/blueprint/src/lib/components/datasets/huggingface/SplitsInput.svelte
  web/blueprint/src/routes/datasets/new/+page.svelte
  web/blueprint/src/routes/rag/+page.svelte
Labels: frontend, backend

#742 Extract the dropdown+pill into a `DropPill` component
  web/blueprint/src/lib/components/common/DropdownPill.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/GroupByDropdown.svelte
  web/blueprint/src/lib/components/datasetView/GroupByPill.svelte
  web/blueprint/src/lib/components/datasetView/SortPill.svelte
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#744 Make llama-index an optional dependency.
  lilac/signal.py
  lilac/sources/github_source.py
  lilac/sources/llama_index_docs_source.py
  notebooks/LlamaIndexLoader.ipynb
  poetry.lock
  pyproject.toml
Labels: backend

#745 Bug fixes for deploy scripts.
  lilac/data/dataset_duckdb.py
  lilac/load.py
  lilac/project.py
  lilac/signal.py
  lilac_hf_space.yml
  scripts/deploy_demo.py
Labels: backend

#748 Make labels toggle-able
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
  web/blueprint/src/lib/components/common/DropdownPill.svelte
  web/blueprint/src/lib/components/datasetView/AddLabel.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/LabelPill.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
Labels: frontend, backend

#750 Add lilac docker image and use a lighter 5x image for HF
  Dockerfile
  README.md
  lilac/data/dataset_duckdb.py
  lilac/hf_docker/Dockerfile
  lilac/hf_docker/docker_start.sh
  lilac/sources/duckdb_utils.py
  lilac/sources/sqlite_source.py
  poetry.lock
  pyproject.toml
Labels: backend

#754 Fix duplicate stats requests
  web/blueprint/src/lib/components/datasetView/GroupByPill.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/lib/stores/datasetStore.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/datasets/+page.svelte
Labels: frontend

#759 Fix port on HF demo since we use app_port: 5432
  lilac/hf_docker/Dockerfile
  lilac/hf_docker/docker_start.sh
  scripts/deploy_demo.py
Labels: backend

#760 Tiny UI fixes
  lilac/data/dataset.py
  lilac/signals/concept_scorer.py
  web/blueprint/src/lib/components/JSONSchema/JSONSchemaInput.svelte
Labels: frontend, backend

#758 Use HDBSCAN for the public demo.
  lilac/signals/cluster_hdbscan.py
  lilac_hf_space.yml
Labels: backend

#762 Batch row metadata requests.
  docs/index.rst
  package-lock.json
  web/blueprint/package.json
  web/blueprint/src/lib/components/HuggingFaceSpaceWelcome.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend

#763 Improve labeling flow
  lilac/deploy.py
  lilac/router_dataset.py
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/datasetView/EditLabel.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
Labels: frontend, backend

#764 Improve dataset load onboarding flow.
  lilac/config.py
  lilac/data/dataset_config_test.py
  lilac/embeddings/embedding.py
  lilac/embeddings/gte.py
  lilac/router_signal.py
  lilac/source.py
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/contextMenu/SchemaFieldMenu.svelte
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetLoadingPage.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/DownloadFieldList.svelte
  web/blueprint/src/lib/components/datasetView/EditLabel.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/GroupByPill.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasetView/SearchPill.svelte
  web/blueprint/src/lib/components/datasetView/SortPill.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/components/schemaView/SchemaView.svelte
  web/blueprint/src/lib/stores/datasetStore.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/concepts/+page.svelte
  web/blueprint/src/routes/datasets/+page.svelte
  web/blueprint/src/routes/datasets/loading/+page.svelte
Labels: frontend, backend

#768 Add `include_labels` and `exclude_labels` when exporting data via `dataset.to_*`
  .env
  docs/.gitignore
  docs/README.md
  docs/conf.py
  docs/datasets/dataset_export.md
  docs/datasets/dataset_labels.md
  docs/huggingface/huggingface_spaces.md
  docs/poetry.lock
  docs/projects/projects.md
  docs/pyproject.toml
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_labels_test.py
  lilac/data/dataset_select_rows_filter_test.py
  lilac/schema.py
  scripts/deploy_website.py
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/datasetView/FilterPill.svelte
  web/lib/fastapi_client/models/MetadataSearch.ts
  web/lib/fastapi_client/models/UnaryFilter.ts
Labels: frontend, backend, client lib

#769 Add the simplest dataset.map()
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_utils.py
  lilac/load_dataset_test.py
  lilac/schema.py
  lilac/tasks.py
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/Field.ts
  web/lib/fastapi_client/models/MapInfo.ts
Labels: backend, client lib

#774 Remove TextSplitterSignal, fixing related tests.
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/signal.py
  lilac/signal_test.py
  lilac/splitters/chunk_splitter.py
  lilac/splitters/chunk_splitter_test.py
  lilac/splitters/text_splitter_spacy.py
  lilac/splitters/text_splitter_spacy_test.py
  lilac/splitters/text_splitter_test_utils.py
Labels: backend

#773 Add sampling to our `ParquetSource`
  .env
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_labels_test.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_test.py
  lilac/env.py
  lilac/load_dataset_test.py
  lilac/schema.py
  lilac/signals/cluster_dbscan.py
  lilac/signals/cluster_hdbscan.py
  lilac/sources/csv_source.py
  lilac/sources/duckdb_utils.py
  lilac/sources/json_source.py
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
  lilac/sources/sqlite_source.py
  pytest.ini
Labels: backend

#775 Improve the Export Dataset modal dialog
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/router_dataset.py
  lilac/router_utils.py
  web/blueprint/src/lib/components/ApiErrorModal.svelte
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/DownloadModal.svelte
  web/blueprint/src/lib/components/datasetView/ExportModal.svelte
  web/blueprint/src/lib/components/datasetView/FieldList.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ExportOptions.ts
  web/lib/fastapi_client/services/DatasetsService.ts
Labels: frontend, backend, client lib

#780 Fix the concept labeler with the new preview concept key.
  web/blueprint/src/lib/components/concepts/labeler_utils.ts
Labels: frontend

#782 Improve export preview text.
  web/blueprint/src/lib/components/datasetView/ExportModal.svelte
Labels: frontend

#777 Upgrade ruff version and fix associated new linter errors
  lilac/data/dataset.py
  lilac/embeddings/vector_store.py
  lilac/schema.py
  lilac/signal.py
  lilac/signals/minhash_dup.py
  poetry.lock
  pyproject.toml
  scripts/fix_py.sh
  scripts/lint_py.sh
  scripts/test_py.sh
Labels: backend

#783 Allow searching by pre-computed concepts in the searchbox.
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
Labels: frontend

#784 Add spacy embedding-clustering splitter
  lilac/splitters/chunk_splitter_test.py
  lilac/splitters/spacy_splitter.py
  lilac/splitters/spacy_splitter_test.py
  lilac/splitters/text_splitter_spacy.py
  lilac/splitters/text_splitter_spacy_test.py
  lilac/splitters/text_splitter_test_utils.py
Labels: backend

#792 Fix a flaky test
  lilac/concepts/profanity/concept.json
  lilac/sources/parquet_source_test.py
  poetry.lock
  pyproject.toml
Labels: backend

#791 Swap in new embedding-chunked splitter algorithm
  lilac/embeddings/gte.py
  lilac/signals/default_signals.py
  lilac/splitters/spacy_splitter.py
  lilac/splitters/spacy_splitter_test.py
  poetry.lock
  pyproject.toml
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
Labels: backend, client lib

#795 Improve ergonomics of map().
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_test.py
  lilac/tasks.py
  notebooks/DatasetMap.ipynb
Labels: backend

#796 Switch splitter to new algorithm, fixing last blocking bug.
  lilac/embeddings/cohere.py
  lilac/embeddings/gte.py
  lilac/embeddings/openai.py
  lilac/embeddings/palm.py
  lilac/embeddings/sbert.py
  lilac/schema.py
Labels: backend

#797 Add the language model reference concept to Lilac.
  lilac/concepts/language-model-reference/concept.json
Labels: backend

#798 Add more examples to the language model reference.
  lilac/concepts/language-model-reference/concept.json
Labels: backend

#804 Hardcode sentence_transformer batch size to 1024 for optimal length-sorting/padding.
  lilac/embeddings/gte.py
  lilac/embeddings/sbert.py
  lilac/embeddings/transformer_utils.py
  notebooks/unmaintained/sentence_transformer_batch_size_perf.ipynb
Labels: backend

#806 Fix NaT bug
  lilac/data/dataset.py
Labels: backend

#807 Fix topk on an indexed repeated field + metadata filter
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/embeddings/vector_store.py
  lilac/router_utils.py
  lilac/server_dataset_test.py
  lilac/signal.py
  lilac/signals/concept_scorer.py
  lilac/signals/concept_scorer_test.py
  lilac/signals/semantic_similarity.py
  web/blueprint/src/lib/components/datasetView/ItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
Labels: frontend, backend

#793 PaLM gcp connector
  lilac/embeddings/palm.py
  mypy.ini
  poetry.lock
  pyproject.toml
Labels: backend

#808 Add JSONL caching for dataset.map().
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/utils.py
  notebooks/DatasetMap.ipynb
Labels: backend
