Repository lilacai/lilac, pull requests merged in 2023-08, with the labels that each got.

#487 Fix a few small UI bugs
  data/concept/lilac/profanity/concept.json
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_settings_test.py
  web/blueprint/src/lib/components/datasetView/DownloadFieldList.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasets/huggingface/DatasetNameInput.svelte
  web/blueprint/src/lib/components/datasets/huggingface/SplitsInput.svelte
  web/blueprint/src/lib/queries/huggingfaceQueries.ts
Labels: frontend, backend

#484 Add batching support to concepts.
  lilac/batch_utils.py
  lilac/batch_utils_test.py
  lilac/concepts/concept.py
  lilac/concepts/db_concept_test.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_test.py
  lilac/data/dataset_utils.py
  lilac/data/dataset_utils_test.py
  lilac/embeddings/embedding.py
  lilac/embeddings/embedding_test.py
  lilac/embeddings/vector_store.py
  lilac/router_concept.py
  lilac/router_signal.py
  lilac/router_utils.py
  lilac/schema.py
  lilac/server_concept_test.py
  lilac/server_signal_test.py
  lilac/signals/concept_labels.py
  lilac/signals/concept_labels_test.py
  lilac/signals/concept_scorer.py
  lilac/signals/concept_scorer_test.py
  lilac/signals/lang_detection.py
  lilac/signals/lang_detection_test.py
  lilac/signals/ner.py
  lilac/signals/pii.py
  lilac/signals/pii_ip_address.py
  lilac/signals/pii_secrets.py
  lilac/signals/semantic_similarity.py
  lilac/signals/semantic_similarity_test.py
  lilac/signals/signal.py
  lilac/signals/splitters/chunk_splitter.py
  lilac/signals/splitters/text_splitter_spacy.py
  lilac/signals/splitters/text_splitter_test_utils.py
  lilac/signals/splitters/text_splitter_test_utils_test.py
  lilac/signals/substring_search.py
  lilac/utils.py
  web/blueprint/src/lib/components/concepts/ConceptPreview.svelte
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ScoreResponse.ts
  web/lib/fastapi_client/models/SignalComputeOptions.ts
  web/lib/fastapi_client/models/SignalComputeResponse.ts
  web/lib/fastapi_client/models/SignalSchemaOptions.ts
  web/lib/fastapi_client/models/SignalSchemaResponse.ts
  web/lib/fastapi_client/services/ConceptsService.ts
  web/lib/fastapi_client/services/SignalsService.ts
Labels: frontend, backend, client lib

#489 Replace sort with a select
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
Labels: frontend

#490 Fix snippeting when there are empty arrays.
  lilac/config.py
  scripts/deploy_hf.py
  web/blueprint/src/lib/view_utils.ts
Labels: frontend, backend

#491 Fix several UI bugs
  web/blueprint/src/app.html
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/components/datasetView/SpanClick.ts
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/datasets/huggingface/HFNameInput.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/lib/stores/taskMonitoringStore.ts
  web/blueprint/src/lib/stores/urlHashStore.ts
  web/blueprint/src/routes/+layout.svelte
  web/blueprint/src/routes/concepts/+page.svelte
  web/blueprint/src/routes/datasets/Datasets.svelte
  web/blueprint/src/routes/datasets/new/+page.svelte
Labels: frontend

#492 Fix preview and add a notebook for migrating old embedding indexes
  lilac/data/__init__.py
  notebooks/MigrateEmbedding.ipynb
  web/blueprint/src/lib/view_utils.ts
  web/lib/src/schema.ts
Labels: frontend, backend, client lib

#493 Improve filter pills
  web/blueprint/src/lib/components/common/RemovableTag.svelte
  web/blueprint/src/lib/components/datasetView/EmbeddingBadge.svelte
  web/blueprint/src/lib/components/datasetView/FilterPill.svelte
  web/blueprint/src/lib/components/datasetView/SearchPill.svelte
  web/blueprint/src/lib/components/datasetView/SignalBadge.svelte
  web/blueprint/src/lib/components/schemaView/FlattenedField.svelte
Labels: frontend

#494 Tiny ui improvements
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/components/schemaView/FlattenedField.svelte
Labels: frontend

#498 Fix z-index for tooltips globally
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/common/HoverTooltip.svelte
  web/blueprint/src/lib/components/datasetView/SpanHoverTooltip.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanDetails.svelte
Labels: frontend

#499 Add side navigation.
  lilac/data/dataset_utils.py
  web/blueprint/src/app.css
  web/blueprint/src/lib/assets/logo.png
  web/blueprint/src/lib/assets/logo_50x50.png
  web/blueprint/src/lib/assets/logo_square.png
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/NavigationGroup.svelte
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/components/datasetView/SpanClick.ts
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/schemaView/SchemaView.svelte
  web/blueprint/src/lib/stores/navigationStore.ts
  web/blueprint/src/lib/utils.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/+layout.svelte
  web/blueprint/src/routes/+page.svelte
  web/blueprint/src/routes/concepts/+page.svelte
  web/blueprint/src/routes/datasets/+page.svelte
  web/blueprint/src/routes/datasets/Datasets.svelte
  web/blueprint/src/routes/datasets/new/+page.svelte
  web/blueprint/src/routes/settings/+page.svelte
Labels: frontend, backend

#503 Semantic search, and concept descriptions
  lilac/concepts/db_concept.py
  lilac/data/dataset_duckdb.py
  lilac/signals/semantic_similarity.py
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/lib/fastapi_client/models/ConceptInfo.ts
Labels: frontend, backend, client lib

#504 Add `GTE` on-device embedding
  lilac/concepts/concept.py
  lilac/embeddings/gte.py
  lilac/embeddings/sbert.py
  lilac/embeddings/transformer_utils.py
  lilac/router_signal.py
  lilac/signals/default_signals.py
  lilac/signals/signal.py
  web/blueprint/src/lib/components/concepts/labeler/Labeler.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
Labels: frontend, backend

#505 Fix the sort regression with topk
  data/concept/lilac/toxicity/concept.json
  lilac/data/dataset_duckdb.py
  lilac/embeddings/gte.py
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
Labels: frontend, backend

#506 Add a signal preview page.
  lilac/router_signal.py
  lilac/router_utils.py
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/concepts/ConceptPreview.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasetView/SpanClick.ts
  web/blueprint/src/lib/components/datasetView/StringSpanDetails.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
  web/blueprint/src/lib/components/schemaView/SchemaView.svelte
  web/blueprint/src/lib/components/signals/SignalView.svelte
  web/blueprint/src/lib/queries/signalQueries.ts
  web/blueprint/src/lib/stores/urlHashStore.ts
  web/blueprint/src/lib/utils.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/+layout.svelte
  web/blueprint/src/routes/signals/+page.svelte
Labels: frontend, backend

#507 Add HNSW vector store, and update the embedding format
  data/concept/lilac/toxicity/concept.json
  lilac/__init__.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_test_utils.py
  lilac/data/dataset_utils.py
  lilac/embeddings/default_vector_stores.py
  lilac/embeddings/embedding.py
  lilac/embeddings/vector_store.py
  lilac/embeddings/vector_store_hnsw.py
  lilac/embeddings/vector_store_numpy.py
  lilac/embeddings/vector_store_test.py
  lilac/signals/concept_scorer_test.py
  lilac/signals/semantic_similarity_test.py
  mypy.ini
  poetry.lock
  pyproject.toml
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
Labels: frontend, backend

#508 Remove implicit negatives and update the concept creation UI to sample from dataset.
  lilac/concepts/concept.py
  lilac/concepts/db_concept.py
  lilac/concepts/db_concept_test.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/embeddings/vector_store.py
  lilac/embeddings/vector_store_hnsw.py
  lilac/embeddings/vector_store_numpy.py
  lilac/router_concept.py
  lilac/signals/concept_scorer.py
  lilac/signals/concept_scorer_test.py
  lilac/signals/semantic_similarity_test.py
  web/blueprint/src/lib/components/commands/CommandCreateConcept.svelte
  web/blueprint/src/lib/components/commands/Commands.svelte
  web/blueprint/src/lib/components/commands/ExamplesList.svelte
  web/blueprint/src/lib/components/concepts/ConceptPreview.svelte
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/queries/conceptQueries.ts
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ConceptColumnInfo.ts
  web/lib/fastapi_client/models/ConceptModelInfo.ts
  web/lib/fastapi_client/models/ConceptScoreSignal.ts
  web/lib/fastapi_client/services/ConceptsService.ts
Labels: frontend, backend, client lib

#510 Add a load script which reads a yml file that configures a lilac instance.
  .gitignore
  README.md
  demo.yml
  lilac/auth.py
  lilac/cli.py
  lilac/concepts/db_concept.py
  lilac/config.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_utils.py
  lilac/data/duckdb_utils.py
  lilac/data_loader.py
  lilac/embeddings/cohere.py
  lilac/embeddings/openai.py
  lilac/embeddings/palm.py
  lilac/embeddings/transformer_utils.py
  lilac/env.py
  lilac/load.py
  lilac/router_concept.py
  lilac/router_data_loader.py
  lilac/router_dataset.py
  lilac/router_google_login.py
  lilac/server.py
  lilac/signals/signal.py
  lilac/sources/gmail_source.py
  lilac/tasks.py
  lilac/utils.py
  mypy.ini
  poetry.lock
  pyproject.toml
  scripts/deploy_hf.py
  web/blueprint/src/routes/datasets/new/+page.svelte
Labels: frontend, backend

#514 Fix clicks on side menu
  web/blueprint/src/lib/components/NavigationGroup.svelte
Labels: frontend

#513 Add a deploy_demo script which deploys our public demo.
  demo.yml
  lilac/cli.py
  lilac/config.py
  lilac/data/dataset.py
  lilac/load.py
  scripts/deploy_demo.py
  scripts/deploy_hf.py
Labels: backend

#516 Add a lock when we do model synching
  data/concept/lilac/profanity/concept.json
  data/concept/lilac/toxicity/concept.json
  lilac/concepts/db_concept.py
  lilac/concepts/db_concept_test.py
  lilac/data/dataset_duckdb.py
  lilac/router_concept.py
  lilac/router_utils.py
  lilac/signals/concept_scorer.py
  lilac/signals/concept_scorer_test.py
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
Labels: frontend, backend

#517 Fix orphaned hover tooltips
  data/concept/lilac/profanity/concept.json
  data/concept/lilac/toxicity/concept.json
  lilac/concepts/concept.py
  lilac/concepts/db_concept_test.py
  lilac/data/dataset_duckdb.py
  lilac/embeddings/vector_store_hnsw.py
  lilac/signals/concept_scorer.py
  lilac/signals/lang_detection.py
  lilac/signals/near_dup.py
  web/blueprint/src/lib/components/datasetView/SpanHover.ts
Labels: frontend, backend

#518 Keep the config.yml file in sync when updating settings, running signals and embeddings.
  README.md
  lilac/config.py
  lilac/data/dataset.py
  lilac/data/dataset_config_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_settings_test.py
  lilac/data/dataset_test_utils.py
  lilac/data_loader.py
  lilac/data_loader_test.py
  lilac/load.py
  lilac/router_data_loader.py
  lilac/router_dataset.py
  lilac/server_dataset_test.py
  lilac/sources/source.py
  lilac/sources/source_registry.py
  poetry.lock
  pyproject.toml
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/routes/datasets/new/+page.svelte
  web/lib/fastapi_client/services/DatasetsService.ts
Labels: frontend, backend, client lib

#523 Few cleanups
  lilac/data/dataset_utils.py
  lilac/embeddings/vector_store.py
  lilac/signals/pii_secrets.py
  lilac/sources/__init__.py
  lilac/sources/csv_source.py
  lilac/sources/default_sources.py
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
  web/blueprint/src/lib/components/schemaView/FlattenedField.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/components/schemaView/SchemaView.svelte
  web/blueprint/src/routes/datasets/new/+page.svelte
Labels: frontend, backend

#520 Add popular datasets to the demo.
  demo.yml
  lilac/load.py
  lilac/tasks.py
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend, backend

#526 Add data dir listing (very useful for debugging), adding sampling for HF sources, fix input number UI bug
  lilac/load.py
  lilac/server.py
  lilac/sources/huggingface_source.py
  lilac/templates/list_files.html
  web/blueprint/src/lib/components/JSONSchema/JSONSchemaInput.svelte
  web/blueprint/vite.config.ts
Labels: frontend, backend

#527 Add tags to concepts and datasets.
  data/concept/lilac/legal-termination/concept.json
  lilac/concepts/concept.py
  lilac/concepts/db_concept.py
  lilac/config.py
  lilac/data/dataset_duckdb.py
  lilac/db_manager.py
  lilac/load.py
  lilac/router_dataset.py
  lilac/server.py
  lilac/utils.py
  scripts/deploy_demo.py
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/NavigationGroup.svelte
  web/blueprint/src/lib/view_utils.ts
  web/lib/fastapi_client/models/Concept.ts
  web/lib/fastapi_client/models/ConceptInfo.ts
  web/lib/fastapi_client/models/DatasetInfo.ts
Labels: frontend, backend, client lib

#532 Add python quickstart
  docs/conf.py
  docs/getting_started/quickstart_python.md
  docs/poetry.lock
  docs/pyproject.toml
  lilac/__init__.py
  lilac/data/__init__.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_test.py
  lilac/schema.py
  lilac/signals/__init__.py
  lilac/signals/pii.py
  lilac/sources/csv_source.py
  lilac/sources/duckdb_utils.py
  lilac/sources/gmail_source.py
  lilac/sources/json_source.py
  poetry.lock
  pyproject.toml
  scripts/publish_pip.sh
Labels: backend

#533 Add welcome page and polish some public API
  docs/_static/lilac-welcome.mp4
  docs/getting_started/quickstart_python.md
  docs/welcome.md
  lilac/data/__init__.py
  lilac/data/dataset.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_groups_test.py
  lilac/data/dataset_select_rows_filter_test.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/router_concept.py
  lilac/router_dataset.py
  lilac/router_signal.py
  lilac/router_utils.py
  lilac/signals/__init__.py
  lilac/signals/concept_scorer.py
  lilac/signals/concept_scorer_test.py
  lilac/signals/default_signals.py
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/commands/customComponents/SelectConcept.svelte
  web/blueprint/src/lib/components/concepts/labeler/DataFeeder.svelte
  web/blueprint/src/lib/components/datasetView/FilterPill.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/view_utils.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/BinaryFilter.ts
  web/lib/fastapi_client/models/BinaryOp.ts
  web/lib/fastapi_client/models/Column.ts
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/ListFilter.ts
  web/lib/fastapi_client/models/ListOp.ts
  web/lib/fastapi_client/models/UnaryFilter.ts
  web/lib/fastapi_client/models/UnaryOp.ts
  web/lib/src/lilac.ts
  web/lib/src/schema.ts
Labels: frontend, backend, client lib

#534 Move lilac concepts into the pip package.
  .gitignore
  __init__.py
  docs/concepts/concepts.md
  lilac/cli.py
  lilac/concepts/db_concept.py
  lilac/concepts/db_concept_test.py
  lilac/concepts/legal-termination/concept.json
  lilac/concepts/negative-sentiment/concept.json
  lilac/concepts/positive-sentiment/concept.json
  lilac/concepts/profanity/concept.json
  lilac/concepts/toxicity/concept.json
  lilac/server.py
  lilac/server_concept_test.py
  lilac/utils.py
  pyproject.toml
  scripts/deploy_demo.py
  scripts/deploy_hf.py
Labels: backend

#535 Polish public API and complete quickstart python
  .gitignore
  .vscode/settings.json
  docs/getting_started/quickstart_python.md
  lilac/data/__init__.py
  lilac/data/dataset.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_udf_test.py
  pyproject.toml
  scripts/deploy_website.sh
  web/blueprint/src/lib/components/concepts/labeler/DataFeeder.svelte
  web/blueprint/src/lib/components/concepts/labeler/Labeler.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasetView/SearchPill.svelte
  web/blueprint/src/lib/components/datasetView/SearchPillHoverBody.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ConceptSearch.ts
  web/lib/fastapi_client/models/KeywordSearch.ts
  web/lib/fastapi_client/models/Search.ts
  web/lib/fastapi_client/models/SelectRowsOptions.ts
  web/lib/fastapi_client/models/SelectRowsSchemaOptions.ts
  web/lib/fastapi_client/models/SemanticSearch.ts
  web/lib/src/lilac.ts
Labels: frontend, backend, client lib

#529 Add legal datasets to the demo.
  demo.yml
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
Labels: frontend

#536 Make `rowid` as proper pseudo column (implicit)
  lilac/data/dataset.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_config_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_select_groups_test.py
  lilac/data/dataset_select_rows_filter_test.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_stats_test.py
  lilac/data/dataset_test.py
  lilac/data/dataset_test_utils.py
  lilac/data/dataset_utils.py
  lilac/data_loader.py
  lilac/data_loader_test.py
  lilac/embeddings/vector_store.py
  lilac/load.py
  lilac/schema.py
  lilac/server_dataset_test.py
  lilac/test_utils.py
  web/blueprint/src/lib/components/commands/CommandCreateConcept.svelte
  web/blueprint/src/lib/components/concepts/labeler/DataFeeder.svelte
  web/blueprint/src/lib/components/concepts/labeler_utils.ts
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/lib/src/schema.ts
Labels: frontend, backend, client lib

#538 Fix `dataset.to_*()` export bug and remove extraneous rowid selections
  lilac/cli.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_config_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_select_groups_test.py
  lilac/data/dataset_select_rows_filter_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_stats_test.py
  lilac/data/dataset_test.py
  lilac/server_dataset_test.py
Labels: backend

#541 Sort numeric histograms by value, not count
  web/blueprint/src/lib/components/schemaView/FieldDetails.svelte
Labels: frontend

#542 Add docs for concept tuning. Add toast for concept tuning.
  docs/_static/concepts/concept_labeler.png
  docs/_static/concepts/concept_labels.png
  docs/_static/concepts/concept_tune.png
  docs/concepts/concept_create.md
  docs/concepts/concept_tuning.md
  notebooks/API.ipynb
  web/blueprint/src/lib/components/concepts/ConceptPreview.svelte
  web/blueprint/src/lib/components/datasetView/SpanClick.ts
  web/blueprint/src/lib/components/datasetView/StringSpanDetails.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/stores/notificationsStore.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/+layout.svelte
Labels: frontend

#544 [Docs] Add concept technical details. Add embeddings.
  docs/concepts/concept_technical.md
  docs/concepts/concepts.md
  docs/embeddings/embeddings.md
  docs/index.rst
  lilac/__init__.py
  lilac/embeddings/__init__.py
  lilac/splitters/__init__.py
Labels: backend

#545 Fix HF demo
  Dockerfile
  demo.yml
  docker_start.py
  docker_start.sh
  lilac/server.py
  scripts/deploy_hf.py
Labels: backend

#546 Add load dataset docs.
  docs/_static/dataset/dataset_getting_started.png
  docs/_static/dataset/dataset_load.png
  docs/_static/dataset/dataset_load_tasks.png
  docs/datasets/dataset_load.md
  lilac/sources/__init__.py
  lilac/sources/csv_source.py
  lilac/sources/csv_source_test.py
  lilac/sources/default_sources.py
  lilac/sources/gmail_source.py
  lilac/sources/huggingface_source.py
  lilac/sources/huggingface_source_test.py
  lilac/sources/json_source.py
  lilac/sources/json_source_test.py
  lilac/sources/pandas_source.py
  lilac/sources/pandas_source_test.py
  lilac/sources/parquet_source.py
  lilac/sources/parquet_source_test.py
  lilac/sources/reddit_hf_source.py
  notebooks/API.ipynb
  web/blueprint/src/lib/components/GettingStarted.svelte
  web/blueprint/src/routes/datasets/new/+page.svelte
Labels: frontend, backend

#549 Add documentation for concepts + datasets.
  docs/_static/dataset/dataset_compute_concept.png
  docs/_static/dataset/dataset_compute_concept_results.png
  docs/_static/dataset/dataset_schema_compute_embedding.png
  docs/_static/dataset/dataset_search_compute.png
  docs/_static/dataset/dataset_search_concept.png
  docs/_static/dataset/dataset_search_concept_results.png
  docs/datasets/dataset_concepts.md
  docs/datasets/dataset_explore.md
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/embeddings/__init__.py
  lilac/sources/default_sources.py
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/routes/+layout.svelte
Labels: frontend, backend

#551 Add medical_dialogue, clean up demo.
  demo.yml
  lilac/sources/huggingface_source.py
  notebooks/API.ipynb
  scripts/deploy_demo.py
Labels: backend

#553 Fix search by repeated
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
Labels: frontend

#559 Fix search box padding
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
Labels: frontend

#561 Fix repeated schema bug
  web/blueprint/src/lib/components/schemaView/FlattenedField.svelte
Labels: frontend

#560 Add help dropdown to the UI. Add links to docs.
  README.md
  docs/welcome.md
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
Labels: frontend

#562 Add favicon.
  docs/conf.py
  web/blueprint/src/app.html
  web/blueprint/static/favicon.ico
  web/blueprint/static/favicon.png
Labels: frontend

#563 Fix stats
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_stats_test.py
  lilac/data/dataset_test.py
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
Labels: frontend, backend

#568 Add question concept
  lilac/concepts/question/concept.json
  web/blueprint/src/routes/concepts/+page.svelte
Labels: frontend, backend

#569 Update questions concept with more examples. Fix concept UI bugs.
  demo.yml
  lilac/concepts/concept.py
  lilac/concepts/question/concept.json
  lilac/router_concept.py
  lilac/server_concept_test.py
  web/blueprint/src/lib/components/concepts/ConceptMetrics.svelte
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/components/concepts/labeler/ConceptDataFeeder.svelte
  web/blueprint/src/lib/components/concepts/labeler/ConceptLabeler.svelte
  web/blueprint/src/lib/components/concepts/labeler_utils.ts
  web/blueprint/src/lib/queries/conceptQueries.ts
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/src/lib/utils.ts
  web/blueprint/src/routes/datasets/+page.svelte
  web/lib/fastapi_client/services/ConceptsService.ts
Labels: frontend, backend, client lib

#571 Add source code & non-english concept. Add a section in concept to apply to a dataset outside the labeler.
  lilac/concepts/non-english/concept.json
  lilac/concepts/source-code/concept.json
  lilac/data/dataset_duckdb.py
  web/blueprint/src/lib/components/commands/CommandCreateConcept.svelte
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/components/concepts/DatasetFieldEmbeddingSelector.svelte
  web/blueprint/src/lib/components/concepts/labeler/ConceptDataFeeder.svelte
  web/blueprint/src/lib/components/concepts/labeler/ConceptLabeler.svelte
  web/lib/fastapi_client/models/ConceptType.ts
  web/lib/fastapi_client/models/CreateConceptOptions.ts
Labels: frontend, backend, client lib

#577 Add dataset loading page.
  lilac/concepts/non-english/concept.json
  web/blueprint/src/lib/stores/urlHashStore.ts
  web/blueprint/src/routes/+layout.svelte
  web/blueprint/src/routes/datasets/loading/+page.svelte
  web/blueprint/src/routes/datasets/new/+page.svelte
Labels: frontend, backend

#584 Add docs for forking, fix forking without persistent storage.
  Dockerfile
  docker_start.py
  docs/_static/huggingface/huggingface_duplicate_space.png
  docs/_static/huggingface/huggingface_duplicate_space_machine.png
  docs/_static/huggingface/huggingface_duplicate_space_variables.png
  docs/_static/huggingface/huggingface_space_readme_datasets.png
  docs/conf.py
  docs/environment/variables.md
  docs/huggingface/huggingface_spaces.md
  docs/index.rst
  docs/welcome.md
  lilac/__init__.py
  lilac/env.py
  web/blueprint/src/lib/components/GettingStarted.svelte
  web/blueprint/src/routes/datasets/new/+page.svelte
Labels: frontend, backend

#589 Release new pip with the latest public API
  lilac/sources/pandas_source.py
  notebooks/API.ipynb
  pyproject.toml
Labels: backend

#591 Rename pip package `lilacai` to `lilac`
  README.md
  development.md
  docs/getting_started/installation.md
  docs/getting_started/quickstart_python.md
  docs/poetry.lock
  docs/pyproject.toml
  docs/welcome.md
  lilac/__init__.py
  lilac/signals/pii.py
  lilac/sources/gmail_source.py
  pyproject.toml
Labels: backend

#593 Change the huggingface space homepage.
  lilac/auth.py
  lilac/server.py
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/HuggingFaceSpaceWelcome.svelte
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/WelcomeBanner.svelte
  web/blueprint/src/routes/+page.svelte
  web/lib/fastapi_client/models/AuthenticationInfo.ts
Labels: frontend, backend, client lib

#594 Simplify the dataset view page.
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/RowItemMetadata.svelte
  web/blueprint/src/lib/components/datasetView/RowView.svelte
  web/blueprint/src/lib/components/datasetView/spanHighlight.ts
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/components/schemaView/SchemaView.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/src/lib/stores/urlHashStore.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/datasets/+page.svelte
  web/lib/src/utils.ts
Labels: frontend, client lib

#595 Fix last minute bugs
  README.md
  docs/_static/logo.png
  docs/_static/logo_wide.png
  docs/blog/introducing-lilac.md
  docs/concepts/concept_metrics.md
  docs/concepts/concept_tuning.md
  docs/concepts/concept_use.md
  docs/concepts/concepts.md
  docs/datasets/dataset_export.md
  docs/huggingface/huggingface_spaces.md
  docs/index.rst
  docs/signals/signals.md
  docs/welcome.md
  lilac/signals/text_statistics.py
  lilac_hf_space.yml
  web/blueprint/src/lib/components/HuggingFaceSpaceWelcome.svelte
  web/blueprint/src/lib/components/WelcomeBanner.svelte
  web/blueprint/src/lib/components/concepts/ConceptPreview.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/+page.svelte
Labels: frontend, backend

#596 Add filter options along source and signal fields
  web/blueprint/src/lib/components/commands/CommandCreateConcept.svelte
  web/blueprint/src/lib/components/commands/selectors/FieldSelect.svelte
  web/blueprint/src/lib/components/concepts/DatasetFieldEmbeddingSelector.svelte
  web/blueprint/src/lib/components/contextMenu/SchemaFieldMenu.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/DownloadFieldList.svelte
  web/blueprint/src/lib/components/datasetView/DownloadModal.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/FilterPill.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/view_utils.ts
  web/lib/src/lilac.spec.ts
  web/lib/src/lilac.ts
Labels: frontend, client lib

#598 Fix discord links
  README.md
  docs/welcome.md
  web/blueprint/src/lib/components/Page.svelte
Labels: frontend

#603 Simplify the search bar
  web/blueprint/src/app.css
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/FilterPill.svelte
  web/blueprint/src/lib/components/datasetView/RowItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/components/schemaView/SchemaView.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/+layout.svelte
  web/lib/src/lilac.ts
Labels: frontend, client lib

#609 Use pip for the HuggingFace demos.
  Dockerfile
  docs/huggingface/huggingface_spaces.md
  docs/signals/signals_create.md
  lilac/cli.py
  lilac/env.py
  lilac/server.py
  scripts/deploy_demo.py
  scripts/deploy_hf.py
  scripts/make_fastapi_client.py
  scripts/publish_pip.sh
  web/blueprint/src/lib/components/GoogleAnalytics.svelte
  web/blueprint/src/lib/queries/serverQueries.ts
  web/blueprint/src/routes/+layout.svelte
  web/blueprint/vite.config.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ServerStatus.ts
  web/lib/fastapi_client/services/DefaultService.ts
Labels: frontend, backend, client lib

#613 Fix paths on windows
  lilac/concepts/db_concept.py
Labels: backend

#612 Make db.select_groups work with python 3.11
  .github/workflows/python.yml
  .github/workflows/typescript.yml
  lilac/data/dataset_duckdb.py
  lilac/schema.py
Labels: backend

#616 Check that gh is installed before publishing to pip so it doesn't fail at the end.
  scripts/publish_pip.sh
Labels: ignore-for-release

#618 Upgrade pytest to fix dependapot vuln
  poetry.lock
  pyproject.toml
Labels: ignore-for-release

#617 Set up auto-configs for release notes with new tags.
  .github/release.yml
Labels: ignore-for-release

#620 Improve memory usage of `lilac load` to unblock mosaic datasets
  lilac/cli.py
  lilac/config.py
  lilac/data/dataset_duckdb.py
  lilac/embeddings/vector_store.py
  lilac/load.py
  lilac/tasks.py
  scripts/deploy_demo.py
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
Labels: frontend, backend

#621 Add a project_path to lilac_start.
  .env
  README.md
  docs/datasets/dataset_load.md
  docs/datasets/dataset_signals.md
  docs/getting_started/installation.md
  docs/getting_started/quickstart.md
  docs/signals/signals_create.md
  docs/welcome.md
  lilac/__init__.py
  lilac/cli.py
  lilac/config.py
  lilac/env.py
  lilac/load.py
  lilac/project.py
  lilac/project_test.py
  lilac/router_data_loader.py
  lilac/router_dataset.py
  lilac/router_tasks.py
  lilac/server.py
  lilac/tasks.py
  run_server_dev.sh
  web/blueprint/src/lib/stores/taskMonitoringStore.ts
  web/blueprint/vite.config.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/TaskInfo.ts
  web/lib/fastapi_client/models/TaskType.ts
  web/lib/fastapi_client/services/DefaultService.ts
Labels: frontend, backend, client lib

#626 Add LangSmith source
  .env
  lilac/__init__.py
  lilac/data/dataset.py
  lilac/data/dataset_test_utils.py
  lilac/embeddings/vector_store.py
  lilac/embeddings/vector_store_hnsw.py
  lilac/schema.py
  lilac/server.py
  lilac/signals/concept_scorer_test.py
  lilac/sources/csv_source.py
  lilac/sources/default_sources.py
  lilac/sources/langsmith.py
  lilac/sources/source.py
  lilac/utils.py
  mypy.ini
  poetry.lock
  pyproject.toml
  web/blueprint/src/lib/components/datasets/langsmith/DatasetInput.svelte
  web/blueprint/src/lib/queries/langsmithQueries.ts
  web/blueprint/src/routes/datasets/new/+page.svelte
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/services/LangsmithService.ts
Labels: frontend, backend, client lib

#622 Fix auth bugs with concepts. Pip install lilac[all] in the dockerfile.
  Dockerfile
  docs/getting_started/quickstart_python.md
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/commands/CommandCreateConcept.svelte
  web/blueprint/src/lib/components/concepts/ConceptExampleList.svelte
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/components/datasetView/RowItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#624 Add ability to make concepts public.
  lilac/concepts/concept.py
  lilac/concepts/db_concept.py
  lilac/concepts/db_concept_test.py
  lilac/concepts/legal-termination/concept.json
  lilac/concepts/negative-sentiment/concept.json
  lilac/concepts/non-english/concept.json
  lilac/concepts/positive-sentiment/concept.json
  lilac/concepts/profanity/concept.json
  lilac/concepts/question/concept.json
  lilac/concepts/source-code/concept.json
  lilac/concepts/toxicity/concept.json
  lilac/router_concept.py
  lilac/server_concept_test.py
  scripts/deploy_hf.py
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/commands/CommandCreateConcept.svelte
  web/blueprint/src/lib/components/commands/selectors/CommandSelectList.svelte
  web/blueprint/src/lib/components/concepts/ConceptSettingsModal.svelte
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/components/datasetView/StringSpanHighlight.svelte
  web/blueprint/src/lib/queries/conceptQueries.ts
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/lib/view_utils.ts
  web/blueprint/src/routes/concepts/+page.svelte
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/Concept.ts
  web/lib/fastapi_client/models/ConceptInfo.ts
  web/lib/fastapi_client/models/ConceptMetadata.ts
  web/lib/fastapi_client/models/CreateConceptOptions.ts
  web/lib/fastapi_client/services/ConceptsService.ts
Labels: frontend, backend, client lib
