Repository lilacai/lilac, pull requests merged in 2024-01, with the labels that each got.

#1009 Add Jina (Small) on Garden signal
  lilac/batch_utils.py
  lilac/data/dataset_duckdb.py
  lilac/embeddings/jina_garden.py
  lilac/signals/default_signals.py
  mypy.ini
  poetry.lock
  pyproject.toml
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
Labels: backend, client lib

#1010 Add `dataset.cluster(remote=True)` bit
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_config_test.py
  lilac/data/dataset_duckdb.py
  lilac/embeddings/jina.py
  lilac/embeddings/jina_garden.py
  lilac/signals/__init__.py
  lilac/signals/cluster_dbscan.py
  lilac/signals/cluster_dbscan_test.py
  lilac/signals/cluster_hdbscan.py
  lilac/signals/cluster_hdbscan_test.py
  lilac/signals/default_signals.py
  lilac_hf_space.yml
  web/blueprint/src/lib/components/commands/CommandSignals.svelte
Labels: frontend, backend

#1013 Fix issue where we don't block on the server thread from the CLI.
  lilac/cli.py
  lilac/server.py
Labels: backend

#1014 Load datasets in a separate thread from the UI.
  lilac/router_data_loader.py
Labels: backend

#1015 Fix issue with repeated of string rendering.
  web/blueprint/src/lib/components/datasetView/DatasetLoadingPage.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
Labels: frontend

#1016 Fix signal configs to use ClassVar
  lilac/embeddings/cohere.py
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  lilac/embeddings/jina_garden.py
  lilac/embeddings/openai.py
  lilac/embeddings/palm.py
  lilac/embeddings/sbert.py
  lilac/signal.py
  lilac/signal_test.py
  lilac/signals/text_statistics.py
  web/lib/fastapi_client/models/ConceptLabelsSignal.ts
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
  web/lib/fastapi_client/models/Signal.ts
  web/lib/fastapi_client/models/SubstringSignal.ts
  web/lib/fastapi_client/models/TextEmbeddingSignal.ts
  web/lib/fastapi_client/models/TextSignal.ts
Labels: backend, client lib

#1022 Improve the title generation in clustering
  lilac/data/clustering.py
Labels: backend

#1023 Add a 2-feature pivot view, allowing you to view a hierarchy of 2 features
  lilac/load.py
  lilac/load_test.py
  lilac/server.py
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/blueprint/src/lib/stores/datasetViewStore.ts
Labels: frontend, backend

#1024 Improve the UI around deleting.
  web/blueprint/src/lib/components/ButtonDropdown.svelte
  web/blueprint/src/lib/components/datasetView/DeleteRowsButton.svelte
  web/blueprint/src/lib/components/datasetView/RestoreRowsButton.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/components/schemaView/SchemaView.svelte
Labels: frontend

#1026 Allows non folder exports
  lilac/router_dataset.py
Labels: backend

#1025 Fixes incorrect destructuring
  lilac/concepts/concept.py
Labels: backend

#1028 Add keyboard shortcuts for fast labeling.
  lilac/config.py
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsKeyboardShortcuts.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/lib/fastapi_client/models/DatasetUISettings.ts
Labels: frontend, backend, client lib

#1031 Fix some `map(overwrite=True)` bugs
  lilac/data/cluster_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_utils.py
Labels: backend

#1032 Add superclusters (categories)
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
Labels: backend

#1033 Improve auto-binning, and sorting of histograms.
  lilac/data/dataset_duckdb.py
  web/blueprint/src/lib/components/schemaView/FieldDetails.svelte
  web/blueprint/src/lib/components/schemaView/Histogram.svelte
Labels: frontend, backend

#1034 Convert the pivot viewer to a bunch of carousels.
  package-lock.json
  web/blueprint/package.json
  web/blueprint/src/lib/carousel.d.ts
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
Labels: frontend

#1035 Remove an extra temporary column at the end of clustering
  lilac/data/cluster_test.py
  lilac/data/clustering.py
Labels: backend

#1038 Fix a bug with OpenAI embeddings after upgrading.
  lilac/embeddings/openai.py
  web/blueprint/src/lib/components/commands/CommandSignals.svelte
Labels: frontend, backend

#1040 Fix a bug with CSV source reader for TSV files, and named columns.
  lilac/sources/csv_source.py
Labels: backend

#1041 Propagate filters in the group by panel
  web/blueprint/src/lib/components/datasetView/GroupByPanel.svelte
Labels: frontend

#1042 Add `dataset.cluster(input)` where `input` can be any lambda func
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
Labels: backend

#1045 Add clustering in the UI
  lilac/auth.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/load_dataset.py
  lilac/router_dataset_signals.py
  lilac/server_test.py
  lilac/signals/default_signals.py
  lilac/tasks.py
  web/blueprint/src/lib/components/ComputeClusterModal.svelte
  web/blueprint/src/lib/components/contextMenu/SchemaFieldMenu.svelte
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ClusterOptions.ts
  web/lib/fastapi_client/models/ClusterResponse.ts
  web/lib/fastapi_client/models/DatasetUserAccess.ts
  web/lib/fastapi_client/services/DatasetsService.ts
  web/lib/src/schema.ts
Labels: frontend, backend, client lib

#1044 Fix bug with ItemMedia not rendering media fields that are deeply nested siblings.
  lilac_hf_space.yml
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
Labels: frontend

#1048 Fix clustering an enriched field
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset_duckdb.py
  lilac/schema.py
Labels: backend

#1049 Add remote computation for the jina embedding
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/embeddings/cohere.py
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  lilac/embeddings/jina_garden.py
  lilac/embeddings/openai.py
  lilac/embeddings/palm.py
  lilac/embeddings/sbert.py
  lilac/router_dataset_signals.py
  lilac/signal.py
  lilac/signal_test.py
  lilac/signals/default_signals.py
  lilac/signals/text_statistics.py
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ClusterInfo.ts
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/Field.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
Labels: backend, client lib

#1050 Add clusters to the schema menu. Migrate to a custom carousel component so the page doesn't freeze.
  package-lock.json
  web/blueprint/package.json
  web/blueprint/src/lib/components/common/Carousel.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/lib/src/lilac.ts
Labels: frontend, client lib

#1051 `dataset.cluster()` flattens any repeated before clustering
  lilac/batch_utils.py
  lilac/batch_utils_test.py
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/schema.py
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/lib/fastapi_client/models/ClusterInfo.ts
  web/lib/src/schema.ts
Labels: frontend, backend, client lib

#1054 Add search to the cluster UI. Add some polish.
  web/blueprint/src/lib/carousel.d.ts
  web/blueprint/src/lib/components/common/Carousel.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/blueprint/src/lib/view_utils.ts
Labels: frontend

#1055 Add a notebook for working with concepts from python.
  lilac/concepts/concept.py
  notebooks/UsingConcepts.ipynb
Labels: backend

#1056 Add a download script which downloads a lilac-processed dataset from HuggingFace
  lilac/cli.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_storage_utils.py
  lilac/data/dataset_test.py
  lilac/deploy.py
  lilac/project.py
  lilac/utils.py
Labels: backend

#1057 Streamline lilac deployment
  lilac/cli.py
  lilac/data/dataset_duckdb.py
  lilac/deploy.py
  lilac/hf_docker_start.py
  scripts/deploy_demo.py
  scripts/deploy_staging.py
Labels: backend

#1059 Add an upload dataset script. Some other cleanups.
  lilac/__init__.py
  lilac/cli.py
  lilac/data/__init__.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_labels_test.py
  lilac/data/dataset_storage_utils.py
  lilac/deploy.py
  pytest.ini
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
Labels: frontend, backend

#1058 Improve the cluster titling and fix a few client-side bugs
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_utils.py
  mypy.ini
  poetry.lock
  pyproject.toml
  pytest.ini
  web/blueprint/src/lib/components/datasetView/SingleItemSelectRows.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
Labels: frontend, backend

#1061 Add documentation for sharing datasets.
  docs/datasets/dataset_share.md
  docs/index.rst
  docs/poetry.lock
  lilac/__init__.py
Labels: backend

#1060 Add share-gpt specific format selectors.
  lilac/__init__.py
  lilac/data/cluster_test.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_format.py
  lilac/data/dataset_format_test.py
Labels: backend

#1062 Optimize the cluster view page to reduce number of requests
  web/blueprint/src/lib/components/datasetView/SingleItemSelectRows.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/lib/fastapi_client/models/DatasetFormat.ts
Labels: frontend, client lib

#1065 Fix broken links in HuggingFaceSpaceWelcome web component
  web/blueprint/src/lib/components/HuggingFaceSpaceWelcome.svelte
Labels: frontend

#1069 Fix a couple issues with the export menu.
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/ExportModal.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/lib/src/lilac.ts
Labels: frontend, client lib

#1071 Create tasks api to ensure exceptions caught
  lilac/data/dataset_duckdb.py
  lilac/load.py
  lilac/load_dataset.py
  lilac/router_data_loader.py
  lilac/router_dataset_signals.py
  lilac/tasks.py
Labels: backend

#1073 Override the OpenAPI base url when lilac is not being served from /
  web/blueprint/src/routes/+layout.svelte
Labels: frontend

#1074 Tiny UI fix for "Clusters of" and shave off 1 call to dataset.stats in clustering
  lilac/data/clustering.py
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
Labels: frontend, backend

#1075 Make the entire svelte app use relative links
  web/blueprint/src/lib/components/GettingStarted.svelte
  web/blueprint/src/lib/components/Navigation.svelte
  web/blueprint/src/lib/components/concepts/ConceptSettingsModal.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsModal.svelte
  web/blueprint/src/lib/stores/urlHashStore.ts
  web/blueprint/src/lib/utils.ts
  web/blueprint/src/routes/+layout.svelte
  web/blueprint/src/routes/concepts/+page.svelte
  web/blueprint/src/routes/datasets/new/+page.svelte
  web/blueprint/vite.config.ts
Labels: frontend

#1076 Support input selectors from config files.
  lilac/__init__.py
  lilac/config.py
  lilac/data/clustering.py
  lilac/data/clustering_test.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_format.py
  lilac/data/dataset_format_test.py
  lilac/dataset_format.py
  lilac/dataset_format_test.py
  lilac/formats/__init__.py
  lilac/formats/default_formats.py
  lilac/formats/openchat.py
  lilac/formats/openchat_test.py
  lilac/formats/sharegpt.py
  lilac/formats/sharegpt_test.py
  lilac/load.py
  lilac/load_test.py
  lilac/schema.py
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ClusterInfo.ts
  web/lib/fastapi_client/models/ClusterInputFormatSelectorInfo.ts
  web/lib/fastapi_client/models/DatasetFormat.ts
Labels: backend, client lib

#1079 Remove the media path x preferred-embedding logic.
  lilac/load.py
  lilac_hf_space.yml
  poetry.lock
  pyproject.toml
Labels: backend

#1081 Fix bug with keyword search highlighting every field.
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
Labels: frontend

#1083 Ignore folders that don't have a manifest.json and make project config source of truth for dataset listing
  lilac/db_manager.py
Labels: backend

#1082 Add remote computation for GTE
  lilac/config.py
  lilac/data/clustering.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_utils.py
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  lilac/load.py
  lilac/load_test.py
  lilac/signal.py
Labels: backend

#1086 Always sort by rowid to make db results stable
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_labels_test.py
  lilac/data/dataset_map_test.py
  lilac/data/dataset_select_rows_filter_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_test.py
  lilac/data/dataset_test_utils.py
  lilac/load_dataset_test.py
  web/blueprint/src/lib/components/datasetView/ScrollView.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemSelectRows.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
Labels: frontend, backend

#1088 Fix a couple of UI bugs
  web/blueprint/src/lib/components/datasetView/ExportModal.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemSelectRows.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
Labels: frontend

#1084 Fix some small UI bugs.
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
Labels: frontend

#1085 Deploy dataset
  lilac/cli.py
  lilac/config.py
  lilac/data/clustering.py
  lilac/deploy.py
  lilac/embeddings/cohere.py
  lilac/embeddings/embedding.py
  lilac/load.py
  lilac_hf_space.yml
  scripts/deploy_demo.py
  scripts/deploy_staging.py
Labels: backend

#1089 Enable deploying at HEAD for demo as well as staging.
  lilac/deploy.py
  scripts/deploy_demo.py
  scripts/deploy_staging.py
Labels: backend

#1090 Add support for loading custom embeddings.
  docs/datasets/dataset_concepts.md
  docs/datasets/dataset_embeddings.md
  docs/index.rst
  lilac/__init__.py
  lilac/cli.py
  lilac/concepts/db_concept_test.py
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_config_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_load_embedding_test.py
  lilac/data/dataset_project_test.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_select_rows_search_test.py
  lilac/data/dataset_select_rows_sort_test.py
  lilac/data/dataset_select_rows_udf_test.py
  lilac/data/dataset_storage_utils.py
  lilac/data/dataset_test.py
  lilac/data/dataset_utils.py
  lilac/embeddings/embedding.py
  lilac/embeddings/embedding_test.py
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  lilac/embeddings/vector_store.py
  lilac/embeddings/vector_store_hnsw.py
  lilac/embeddings/vector_store_numpy.py
  lilac/hf_docker_start.py
  lilac/load_test.py
  lilac/router_utils.py
  lilac/schema.py
  lilac/server_concept_test.py
  lilac/signal.py
  lilac/signals/__init__.py
  lilac/signals/concept_scorer_test.py
  lilac/signals/default_signals.py
  lilac/signals/semantic_similarity_test.py
  notebooks/CustomEmbeddings.ipynb
  scripts/deploy_demo.py
Labels: backend

#1092 Rename remote => use_garden.
  lilac/config.py
  lilac/data/clustering.py
  lilac/data/clustering_test.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  lilac/load.py
  lilac/load_test.py
  lilac/router_dataset_signals.py
  lilac/schema.py
  lilac/signal.py
  lilac/signal_test.py
  lilac_hf_space.yml
  web/blueprint/src/lib/components/ComputeClusterModal.svelte
  web/blueprint/src/lib/components/Navigation.svelte
  web/lib/fastapi_client/models/ClusterInfo.ts
  web/lib/fastapi_client/models/ClusterOptions.ts
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
Labels: frontend, backend, client lib

#1091 Fix dataset export to avoid flattening the user data
  lilac/data/clustering.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/sources/parquet_source_test.py
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/ExportModal.svelte
Labels: frontend, backend

#1093 Fix a bug where we drop source fields that have embeddings computed on them
  web/blueprint/src/lib/components/datasetView/ExportModal.svelte
  web/lib/src/lilac.ts
Labels: frontend, client lib

#1096 Fix chunking bug for remote embedding computation
  lilac/embeddings/gte.py
  lilac/embeddings/sbert.py
  lilac/splitters/spacy_splitter.py
  lilac/splitters/spacy_splitter_test.py
Labels: backend

#1097 Speed up PII and lang detection by making them multiprocess
  lilac/signals/lang_detection.py
  lilac/signals/pii.py
  lilac/tasks.py
Labels: backend

#1099 Fixed cache busting behavior
  lilac/hf_docker_start.py
Labels: backend

#1098 Bug fixes: overwrite, task errors, embedding keys.
  lilac/data/dataset.py
  lilac/router_dataset_signals.py
  lilac/signal.py
  lilac_hf_space.yml
  web/blueprint/src/lib/components/TaskStatus.svelte
  web/blueprint/src/lib/components/commands/CommandSignals.svelte
  web/lib/fastapi_client/models/ComputeSignalOptions.ts
Labels: frontend, backend, client lib

#1102 Move use_garden outside of a Signal.
  lilac/config.py
  lilac/data/dataset_duckdb.py
  lilac/load.py
  lilac/load_test.py
  lilac/router_dataset_signals.py
  lilac/signal.py
  lilac/signal_test.py
  lilac/signals/pii.py
  lilac_hf_space.yml
  web/blueprint/src/lib/components/commands/CommandSignals.svelte
  web/lib/fastapi_client/models/ComputeSignalOptions.ts
  web/lib/fastapi_client/models/ConceptLabelsSignal.ts
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
  web/lib/fastapi_client/models/Signal.ts
  web/lib/fastapi_client/models/SubstringSignal.ts
  web/lib/fastapi_client/models/TextEmbeddingSignal.ts
  web/lib/fastapi_client/models/TextSignal.ts
Labels: frontend, backend, client lib

#1103 Add accelerated PII execution on Lilac Garden
  lilac/data/dataset_duckdb.py
  lilac/signals/pii.py
  web/blueprint/src/lib/components/datasetView/SingleItemSelectRows.svelte
Labels: frontend, backend

#1106 Small fixes for the demo.
  lilac/data/clustering.py
  lilac/data/clustering_test.py
  lilac/formats/default_formats.py
  lilac/formats/openai_json.py
  lilac/formats/openai_json_test.py
  lilac/formats/sharegpt.py
  lilac/signals/text_statistics.py
  lilac_hf_space.yml
  scripts/deploy_demo.py
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
Labels: frontend, backend

#1109 Couple of small bug fixes
  Dockerfile
  lilac/data/clustering.py
  lilac/hf_docker/Dockerfile
  lilac/router_dataset_signals.py
Labels: backend

#1111 Refactor buttons so we have a single cluster button.
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/schemaView/SchemaView.svelte
Labels: frontend

#1110 Fix edge case where table doesn't exist and doesn't get created
  lilac/data/dataset_duckdb.py
  scripts/deploy_demo.py
Labels: backend

#1112 Fix the cluster sort by membership score bug
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/commands/customComponents/SelectEmbedding.svelte
  web/blueprint/src/lib/components/contextMenu/SchemaFieldMenu.svelte
  web/blueprint/src/lib/components/datasetView/DatasetLoadingPage.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/PrefetchRowItem.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/ScrollView.svelte
  web/blueprint/src/lib/components/datasetView/SearchPill.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemSelectRows.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/components/datasetView/SortPill.svelte
  web/blueprint/src/lib/components/schemaView/SchemaField.svelte
  web/blueprint/src/lib/components/schemaView/SchemaView.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
  web/lib/src/schema.ts
Labels: frontend, client lib

#1113 Export to HuggingFace. Support glaive-function-calling-v2 in the demo, clusters, and via sharegpt.
  README.md
  docs/welcome.md
  lilac/__init__.py
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/data/dataset_storage_utils.py
  lilac/db_manager.py
  lilac/formats/sharegpt.py
  lilac_hf_space.yml
  notebooks/GlaiveToShareGPT.ipynb
  run_server_dev.sh
  web/blueprint/src/lib/components/HuggingFaceSpaceWelcome.svelte
  web/blueprint/src/lib/view_utils.ts
Labels: frontend, backend

#1114 Add a clustering guide
  docs/_static/dataset/dataset_cluster.png
  docs/_static/dataset/dataset_cluster_modal.png
  docs/_static/dataset/dataset_cluster_view.png
  docs/_static/dataset/dataset_open_clusters.png
  docs/datasets/dataset_cluster.md
  docs/datasets/dataset_export.md
  docs/index.rst
  docs/poetry.lock
  notebooks/Clustering.ipynb
  poetry.lock
  scripts/build_docs.sh
  scripts/watch_docs.sh
  web/blueprint/src/lib/components/ComputeClusterModal.svelte
  web/blueprint/src/lib/components/commands/CommandSignals.svelte
Labels: frontend

#1117 Fix a non blocking start_server
  lilac/server.py
  lilac/server_test.py
Labels: backend

#1119 Add eval datasets to the huggingface demo.
  lilac/hf_docker_start.py
  lilac_hf_space.yml
Labels: backend

#1118 Cluster explore link is now a button; doesn't open in new tab
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
Labels: frontend

#1121 Fix a few bugs related to concepts and clustering
  .env
  docs/blog/introducing-lilac.md
  docs/concepts/concept_use.md
  docs/embeddings/embeddings.md
  docs/getting_started/installation.md
  docs/poetry.lock
  lilac/data/clustering.py
  lilac/data/dataset_compute_signal_chain_test.py
  lilac/data/dataset_compute_signal_test.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_rows_schema_test.py
  lilac/data/dataset_test.py
  lilac/data/dataset_utils.py
  lilac/embeddings/palm.py
  lilac/env.py
  lilac/load_test.py
  lilac/router_concept.py
  lilac/schema.py
  lilac/server.py
  lilac/signals/default_signals.py
  lilac_hf_space.yml
  poetry.lock
  pyproject.toml
  web/blueprint/src/lib/components/concepts/ConceptSettingsModal.svelte
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/queries/conceptQueries.ts
  web/blueprint/src/routes/concepts/+page.svelte
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/EmbeddingInfo.ts
  web/lib/fastapi_client/models/Field.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
Labels: frontend, backend, client lib

#1122 Fix concept labeler when we index a repeated string (capybara)
  lilac/embeddings/gte.py
  lilac/embeddings/jina.py
  web/blueprint/src/lib/components/concepts/ConceptMetrics.svelte
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/components/concepts/labeler_utils.ts
  web/lib/src/lilac.ts
Labels: frontend, backend, client lib

#1123 Fix pandas deprecation warning
  lilac/data/dataset_duckdb.py
Labels: backend

#1124 Fix "open dataset and apply concept"
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/components/concepts/DatasetFieldEmbeddingSelector.svelte
  web/blueprint/src/lib/components/concepts/labeler/ConceptLabeler.svelte
Labels: frontend

#1120 Add more demo datasets.
  lilac/formats/default_formats.py
  lilac/formats/openai_json.py
  lilac/formats/openai_json_test.py
  lilac_hf_space.yml
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
Labels: frontend, backend

#1126 Cache dataset.pivot() and make cluster search box more visible
  lilac/data/clustering_test.py
  lilac/data/dataset_duckdb.py
  lilac/load_test.py
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
  web/blueprint/src/lib/view_utils.ts
Labels: frontend, backend

#1129 Fix a few small bugs by testing prod mode
  lilac/cli.py
  poetry.lock
  pyproject.toml
  web/blueprint/src/lib/components/NavigationExpandable.svelte
Labels: frontend, backend

#1128 Add some polish to the clusters page. Fix some other UI bugs.
  lilac/data/dataset.py
  lilac/server.py
  web/blueprint/src/lib/components/common/Carousel.svelte
  web/blueprint/src/lib/components/common/DropdownPill.svelte
  web/blueprint/src/lib/components/datasetView/Dataset.svelte
  web/blueprint/src/lib/components/datasetView/DatasetControls.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
  web/blueprint/src/lib/components/datasetView/FilterControls.svelte
  web/blueprint/src/lib/components/datasetView/FilterPanel.svelte
  web/blueprint/src/lib/components/datasetView/GroupByControls.svelte
  web/blueprint/src/lib/components/datasetView/GroupByPanel.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ScrollView.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/components/datasetView/SortControls.svelte
Labels: frontend, backend

#1131 Add --deploy_at_head to deploy_project. Fix bug with percentages.
  lilac/cli.py
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
Labels: frontend, backend

#1133 Update readme.md
  README.md
  docs/_static/dataset/dataset_cluster_view.png
  docs/getting_started/installation.md
  web/blueprint/src/lib/components/datasetView/DatasetPivotResult.svelte
  web/blueprint/src/lib/components/datasetView/DatasetPivotViewer.svelte
Labels: frontend

#1134 Rename USE_TABLE_INDEX => LILAC_USE_TABLE_INDEX. Add LILAC_PROD_MODE.
  lilac/data/dataset_duckdb.py
  lilac/env.py
  lilac/server.py
  lilac_hf_space.yml
  web/blueprint/src/lib/components/ErrorNotifications.svelte
  web/blueprint/src/routes/+layout.svelte
  web/lib/fastapi_client/models/ServerStatus.ts
Labels: frontend, backend, client lib

#1136 Fix signal info error
  docs/poetry.lock
  lilac/signal.py
  web/blueprint/src/lib/components/signals/SignalView.svelte
Labels: frontend, backend

#1138 Add progress bars for JINA embedding for local clustering
  lilac/data/clustering.py
Labels: backend

#1140 Handle sqlite files separately during table/index creation
  lilac/data/dataset_duckdb.py
  lilac/env.py
Labels: backend

#1143 Fix issue with urls that end with a slash.
  lilac/server.py
  web/blueprint/src/lib/components/NavigationExpandable.svelte
Labels: frontend, backend

#1145 Update Quickstart (UI and python)
  docs/_static/getting_started/orca-cluster.mp4
  docs/getting_started/quickstart.md
  docs/getting_started/quickstart_python.md
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/embeddings/transformer_utils.py
  lilac/load.py
Labels: backend

#1132 Add links to Lilac Garden page
  docs/datasets/dataset_cluster.md
  web/blueprint/src/lib/components/ComputeClusterModal.svelte
  web/blueprint/src/lib/components/commands/CommandSignals.svelte
Labels: frontend

#1147 Update docs - address PR comments from #1145
  docs/getting_started/quickstart.md
  docs/getting_started/quickstart_python.md
  docs/poetry.lock
  lilac/data/dataset.py
Labels: backend

#1151 Fix unusual inputs to auto binning histogram
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_groups_test.py
Labels: backend

#1149 Tiny blog update (remove yet another logo)
  LICENSE
  README.md
  docs/blog/introducing-garden.md
  docs/conf.py
  docs/index.rst
  lilac/hf_docker/LICENSE
Labels: backend

#1154 Implement signal cancellation
  lilac/router_tasks.py
  lilac/tasks.py
  web/blueprint/src/lib/components/TaskStatus.svelte
  web/lib/fastapi_client/services/TasksService.ts
Labels: frontend, backend, client lib

#1156 Add OpenHermes-2.5 to the public demo.
  lilac_hf_space.yml
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
Labels: frontend
