Repository lilacai/lilac, pull requests merged in 2024-02, with the labels that each got.

#1158 Fix errors when the concept is empty
  lilac/concepts/concept.py
  lilac/concepts/db_concept_test.py
Labels: backend

#1159 Fix issue where by default a long media doesnt take up the full screen
  lilac/embeddings/openai.py
  lilac/project_test.py
  web/blueprint/src/lib/components/Page.svelte
  web/blueprint/src/lib/components/datasetView/DatasetControls.svelte
  web/blueprint/src/lib/components/datasetView/DatasetLoadingPage.svelte
  web/blueprint/src/lib/components/datasetView/DatasetSettingsFields.svelte
  web/blueprint/src/lib/components/datasetView/ItemMedia.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaDiff.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
  web/blueprint/src/lib/components/datasetView/ScrollView.svelte
  web/blueprint/src/lib/components/datasetView/SingleItemView.svelte
  web/blueprint/src/lib/monaco.ts
Labels: frontend, backend

#1160 Fix some issues with exporting.
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_export_test.py
  lilac/router_dataset.py
  web/blueprint/src/lib/components/datasetView/ExportModal.svelte
  web/blueprint/src/lib/components/datasetView/FieldList.svelte
  web/lib/fastapi_client/models/ExportOptions.ts
  web/lib/fastapi_client/models/SelectRowsOptions.ts
Labels: frontend, backend, client lib

#1163 Create Cancelled task status
  lilac/tasks.py
  web/lib/fastapi_client/models/TaskStatus.ts
Labels: backend, client lib

#1162 Make the cancel button in the UI work.
  lilac/tasks.py
  web/blueprint/src/lib/components/TaskStatus.svelte
  web/blueprint/src/lib/queries/taskQueries.ts
Labels: frontend, backend

#1165 Power-law histogram generations
  lilac/data/dataset.py
  lilac/data/dataset_duckdb.py
  lilac/data/dataset_select_groups_test.py
  web/blueprint/src/lib/components/schemaView/Histogram.svelte
  web/lib/fastapi_client/models/StatsResult.ts
Labels: frontend, backend, client lib

#1169 Format N/A values separately in histograms
  web/blueprint/src/lib/components/schemaView/Histogram.svelte
Labels: frontend

#1172 Variables for OpenAI API and Model
  .env
  lilac/data/cluster_titling.py
  lilac/embeddings/openai.py
  lilac/gen/generator_openai.py
  lilac/router_concept.py
Labels: backend

#1174 Support the FastAPI app being mounted.
  integration_tests/fastapi_integration.py
  integration_tests/fastapi_mount_test.sh
  integration_tests/run_integration_tests.sh
  integration_tests/start_server_test.sh
  lilac/server.py
Labels: backend

#1175 Change link to selection => copy link to selection.
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
Labels: frontend

#1180 Fix bug with editing filters & keyword search of ''
  web/blueprint/src/lib/components/commands/CommandFilter.svelte
  web/blueprint/src/lib/components/datasetView/SearchPanel.svelte
  web/blueprint/src/lib/stores/datasetViewStore.ts
Labels: frontend

#1179 Fix a few UI issues with concepts & UI bugs
  web/blueprint/src/lib/components/common/DropdownPill.svelte
  web/blueprint/src/lib/components/common/HoverTooltip.svelte
  web/blueprint/src/lib/components/concepts/ConceptView.svelte
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
  web/blueprint/src/lib/components/datasetView/RowItem.svelte
Labels: frontend

#1182 Add bge-m3 and Nomic 1.5 embeddings.
  lilac/data/cluster_titling.py
  lilac/embeddings/bge.py
  lilac/embeddings/nomic_embed.py
  lilac/signals/default_signals.py
  mypy.ini
  poetry.lock
  pyproject.toml
  web/lib/fastapi_client/models/ConceptSignal.ts
  web/lib/fastapi_client/models/SemanticSimilaritySignal.ts
Labels: backend, client lib

#1183 Fix issue with FastAPI mounts.
  integration_tests/fastapi_mount_test.sh
  integration_tests/run_integration_tests.sh
  lilac/data/cluster_titling.py
  lilac/server.py
  lilac/server_mount_test.py
  lilac/server_test.py
Labels: backend

#1185 Add format selectors to the compute clusters UI.
  lilac/data/clustering.py
  lilac/formats/openai_json.py
  lilac/formats/openchat.py
  lilac/formats/sharegpt.py
  lilac/load_test.py
  lilac/router_dataset.py
  lilac/router_dataset_signals.py
  web/blueprint/src/lib/components/ComputeClusterModal.svelte
  web/blueprint/src/lib/components/commands/selectors/FieldSelect.svelte
  web/blueprint/src/lib/queries/datasetQueries.ts
  web/lib/fastapi_client/index.ts
  web/lib/fastapi_client/models/ClusterOptions.ts
  web/lib/fastapi_client/models/DefaultClusterOutputPathOptions.ts
  web/lib/fastapi_client/services/DatasetsService.ts
Labels: frontend, backend, client lib

#1189 Fix bug when theres no dataset format and we fail to cluster.
  web/blueprint/src/lib/components/ComputeClusterModal.svelte
Labels: frontend

#1192 Fix llama-index test after upgrading deps
  lilac/sources/github_source.py
  lilac/sources/llama_index_docs_source.py
  lilac/sources/llama_index_docs_source_test.py
Labels: backend

#1193 Respect the `self._split` param when computing embeddings for a text
  lilac/concepts/concept.py
  lilac/concepts/db_concept.py
  lilac/embeddings/bge.py
  lilac/embeddings/cohere.py
  lilac/embeddings/gte.py
  lilac/embeddings/nomic_embed.py
  lilac/embeddings/openai.py
  lilac/embeddings/sbert.py
  web/blueprint/src/lib/components/datasetView/ItemMediaTextContent.svelte
Labels: frontend, backend

#1195 Fix a bug with excess RAM usage during vector computes.
  lilac/data/dataset_select_rows_sort_test.py
  lilac/embeddings/vector_store.py
  lilac/embeddings/vector_store_hnsw.py
  lilac/embeddings/vector_store_numpy.py
  lilac/embeddings/vector_store_test.py
  lilac/signals/semantic_similarity_test.py
Labels: backend
